### ISSUE TITLE
[Bug] Triggers not released until inventory is opened

### ISSUE THREAD

**Issue by FabianMPunkt** [isXander/Controlify#105]
### Current Behaviour

I press the triggers on my Steam Deck once, and the game acts like i am continuously holding them down, until i open the inventory.

### Expected Behaviour

I press the triggers on my Steam Deck once, and the game should register that as a single press.

### Reproduction Steps

- Press right trigger once
- Aim at block
- Game will break that block as if i never let go of the trigger
- Open inventory (Y)
- Right trigger gets released

Same happens to the left trigger.

### Mod Version

1.4.0+1.20

### Controller

Steam Deck

### Bluetooth

- [ ] Yes

### Operating System

Linux/SteamOS

### ARM

- [ ] Yes

### Additional Information

Restarting the Deck didn't help.
I also removed the mod and all it's config files, so essentially reinstalling it, but that didn't help either.

As a work-around i assigned the triggers to be the mouse buttons via SteamInput.

It started happening only after i updated to 1.4.0+1.20

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by RealVishy** [comment]
Just want to say that i'm also experiencing this issue on 1.4.0+1.20 with my dualsense as well

**Comment by PotatoTheDevil** [comment]
This is also happening to me on my steam deck and also on PC using an Xbox 360 controller, i hope that this gets fixed ASAP, as it makes the game unplayable.

**Comment by PotatoTheDevil** [comment]
This is also happening to me on my steam deck and also on PC using an Xbox 360 controller, i hope that this gets fixed ASAP, as it makes the game unplayable.

**Comment by rayyanimam** [comment]
This also happened to me, though I'm using an Xbox One Controller, and it's happening to both my right trigger and my left trigger.

**Comment by Aquasp102** [comment]
This has also been happening with me when using Controlify on the Steam Deck. I thought it was just an issue on my end, but I guess it isn't. I'm using the current beta version of the 1.20.1 Fabulously Optimized modpack which came with Controlify, and one of the older alpha versions of the modpack I used had Midnight Controls from what I remember, which didn't have this trigger issue.

**Comment by isXander** [comment]
Fixed in 2b41391a737e94070c461a3544c6a5716a5344cf
