### ISSUE TITLE
[Bug] Can't hold down the attack/use button 

### ISSUE THREAD

**Issue by dbrighthd** [isXander/Controlify#106]
### Current Behaviour

I try to hold down the button to attack/use an item and it just treats it as a click. exact opposite of #105  that was just fixed in this update

### Expected Behaviour

It should let me hold down to eat/break blocks

### Reproduction Steps

I connected a nintendo switch controller and tried to break a block

### Mod Version

1.4.1+1.20 (modrinth doesnt have 1.20.1 listed as compatible but that is the minecraft version i am using)

### Controller

https://www.amazon.com/PowerA-Wireless-Controller-Nintendo-Switch-GameCube/dp/B07GXLBCC3

### Bluetooth

- [X] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Additional Information

I am using a gamecube pro controller for nintendo switch

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by RealVishy** [comment]
Experiencing this issue as well on 1.41+1.20, the holding down of the triggers has been resolved but it only acts as a click.
This is the latest.log file with my Dualsense.
[latest.log](https://github.com/isXander/Controlify/files/11994086/latest.log)

**Comment by HasuMigu** [comment]
The same issue occurs with my Steam Deck on Linux, I will edit this to have the log once I have the time. This issue has happened before the break/place stuck bug.

**Comment by Aquasp102** [comment]
I've been experiencing this same issue as well on my Steam Deck using Controlify. And yeah, it is basically the exact opposite issue that was happening in the last version of the mod where the triggers were constantly held down, with them now just registering as one click and can't be held down. Hopefully these issues won't be too difficult to fix.

**Comment by janlothar** [comment]
> I've been experiencing this same issue as well on my Steam Deck using Controlify. And yeah, it is basically the exact opposite issue that was happening in the last version of the mod where the triggers were constantly held down, with them now just registering as one click and can't be held down. Hopefully these issues won't be too difficult to fix.

Yep same here. I used prism to get the latest Fabulously Optimized mod pack to play on my deck, which came with a slightly outdated controlify. That version caused the attack action to become stuck until I opened inventory or pause menu.

After updating to latest controlify, I have the same issue described in this thread, where holding trigger for attacking only attacks once.

**Comment by RealVishy** [comment]
> > I've been experiencing this same issue as well on my Steam Deck using Controlify. And yeah, it is basically the exact opposite issue that was happening in the last version of the mod where the triggers were constantly held down, with them now just registering as one click and can't be held down. Hopefully these issues won't be too difficult to fix.
> 
> Yep same here. I used prism to get the latest Fabulously Optimized mod pack to play on my deck, which came with a slightly outdated controlify. That version caused the attack action to become stuck until I opened inventory or pause menu.
> 
> After updating to latest controlify, I have the same issue described in this thread, where holding trigger for attacking only attacks once.

1.3.2 was the last one that worked for me so I'd recommend staying on that for now until it's fixed

**Comment by PixelPacker** [comment]
> I've been experiencing this same issue as well on my Steam Deck using Controlify. And yeah, it is basically the exact opposite issue that was happening in the last version of the mod where the triggers were constantly held down, with them now just registering as one click and can't be held down. Hopefully these issues won't be too difficult to fix.

I do think it’s worth noting that it also seems to double interact. So it will open and close the door in the same tick.

**Comment by isXander** [comment]
1.4.1 probably fixed this.

**Comment by PixelPacker** [comment]
> 1.4.1 probably fixed this.
1.4.1 Seemed to replace it with a new problem of not being able to hold the use keys. 
This however on steamdeck

**Comment by Crackers0106** [comment]
What I noticed is that whenever I open a door or chest, it seems to play the opening sound twice? I think that might be related

**Comment by Clyxos** [comment]
Experiencing this on 1.4.2 as well with a dualshock 4 controller.
