### ISSUE TITLE
Can't Stop Breaking Blocks[Bug] 

### ISSUE THREAD

**Issue by Donastria** [isXander/Controlify#107]
### Current Behaviour

When I break a block it just doesn't stop breaking them. I am not pressing the button anymore but it is STILL breaking blocks. Same with placing. When I place one it just continues placing forever.

### Expected Behaviour

place or break SINGLE blocks

### Reproduction Steps

open a world with this mod installed
try placing a block or breaking a block

### Mod Version

0.2.0

### Controller

wired xbox one x

### Bluetooth

- [ ] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by RealVishy** [comment]
Is 0.2 the mod version you're using? 1.41 is the latest available version. Have you tried that?

**Comment by Donastria** [comment]
sure hold up and I will get you everything ok?
Controlify-1.4.0+1.20
[latest.log](https://github.com/isXander/Controlify/files/12001130/latest.log)

**Comment by Donastria** [comment]
just tried the new one with the same result. Places multiple blocks at once and same with breaking blocks, breaks multiple at once. as a control test to make sure it isn't something else I have installed I am going to try another controller mod and see if the problem persists...

**Comment by RealVishy** [comment]
> just tried the new one with the same result. Places multiple blocks at once and same with breaking blocks, breaks multiple at once. as a control test to make sure it isn't something else I have installed I am going to try another controller mod and see if the problem persists...

By new one are you referring to 1.4.1 version? That should have fixed the issue of holding down the triggers. Not sure what's happening if that's the case.

**Comment by isXander** [comment]
1.4.1 fixes this. duplicate.
