### ISSUE TITLE
[Bug] Can't move using an Xbox 360 controller

### ISSUE THREAD

**Issue by Luminexus** [isXander/Controlify#110]
### Current Behaviour

I try to move using an Xbox 360 Controller (yes, a 360 controller, laugh all you want) and it doesn't do anything.
I also can't jump.
 Edit: The right stick works, and the mod can detect the Left Stick being clicked
### Expected Behaviour

I actually move using the controller.

### Reproduction Steps

1. Have a 360 controller
2. Attempt to move/jump
3. Fail

### Logs

```shell
(there were no logs related to controlify)
```

### Mod Version

1.4.4+1.20

### Controller

Xbox 360

### Bluetooth

- [ ] Yes

### Operating System

Windows 11

### ARM

- [ ] Yes

### Additional Information

Fabric Loader latest edition

I don't know if this helps, but I use MultiMC to launch games
### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by seanosh** [comment]
Came to see if this was a known issue. Same problem as reporter, but with my kid's controllers from the Xbox Design Lab normally used with a Series X (so maybe not confined to a 360 controller specifically?).

Right stick seemingly works fine, left stick non-responsive along with A and B buttons.

Lemme know if I can help provide any additional required info.

**Comment by Luminexus** [comment]
> Came to see if this was a known issue. Same problem as reporter, but with my kid's controllers from the Xbox Design Lab normally used with a Series X (so maybe not confined to a 360 controller specifically?).
> 
> Right stick seemingly works fine, left stick non-responsive along with A and B buttons.
> 
> Lemme know if I can help provide any additional required info.

Same for me except the B button. B button works fine for me.

**Comment by isXander** [comment]
Try disconnecting and reconnecting with the controller connected. There is a hotplug issue

**Comment by fiteuwu** [comment]
I had this issue on my Xbox One S controller, but I was only trying on multiplayer servers at first. After loading a singleplayer world once and it working it's now also working on multiplayer too.

**Comment by Luminexus** [comment]
@fiteuwu I have tried both and no luck :/

**Comment by SpektacleFR** [comment]
possibly related to #100

**Comment by Luminexus** [comment]
Issue fixed in 1.4.6+1.20. Thanks for all the help!
