### ISSUE TITLE
[Bug] Can't move while playing on the server

### ISSUE THREAD

**Issue by mrdratik** [isXander/Controlify#115]
### Current Behaviour

In singleplayer, everything works fine, but on the server, my character only twitches when the left stick is deflected.
I [read this](https://github.com/isXander/Controlify/issues/15), but here it seems that we are talking about some future custom actions, and not the usual movement.

### Expected Behaviour

I actually move using the controller

### Screenshots

https://github.com/isXander/Controlify/assets/70975567/1d5305de-8ce9-4974-aaa7-035b20ff18af

### Reproduction Steps

Have a xinput bluetooth controller
Attempt to move
Fail

### Mod Version

1.4.4+1.20

### Controller

Gamesir T4 Pro connected as Xbox wireless controller

### Bluetooth

- [X] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isXander** [comment]
This looks like an anti-cheat issue. Try turning on keyboard-like movement in global settings.
