### ISSUE TITLE
Some way to Unbind things completely.

### ISSUE THREAD

**Issue by bigmaxine** [isXander/Controlify#120]
**Is your feature request related to a problem? Please describe.**
Technically no, but it does annoy me as it is in every other controller mod I've used

**Describe the solution you'd like**
When clicking a binding there should be some way to unbind the function, such as what MidnightControls does where it replaces the "Reset" button next to the binding with an "Unbind" button. This could also be a key such as esc or backspace.

good work on the mod btw, I will be switching to this if you guys add this.

**Comment by isXander** [comment]
You can already do this, however it is unintuitive. When the bind is selected, press the right stick down.

**Comment by isXander** [comment]
Making the reset button set to none is a better idea however.
