### ISSUE TITLE
[Controller Request] Dualsense Edge Support

### ISSUE THREAD

**Issue by swaggio7** [isXander/Controlify#121]
**Controller name**
Dualsense Edge

**Conroller VID & PID**

[latest.log](https://github.com/isXander/Controlify/files/12186429/latest.log)
"[20:49:14] [main/INFO]: I used the json to destroy the json"

**Comment by isXander** [comment]
It has already been detected? 
> Controller found: Dualsense Controller

**Comment by swaggio7** [comment]
> It has already been detected?
Nope, that was an actual DualSense controller that I connected. The Edge doesnt get recognised and is instead an unknown controller.

**Comment by swaggio7** [comment]
Wait, why cant I reopen issues?
