### ISSUE TITLE
[Feature request] d-pad navigation in inventory

### ISSUE THREAD

**Issue by Hikiru** [isXander/Controlify#124]
I’m pretty used to using the d-pad instead of the cursor in bedrock and was pretty disappointed that a cursor is the only option for controlify. It’d be nice to have d-pad navigation in the inventory as well

**Comment by Ivanoshechka** [comment]
I'm really waiting this. I need and left stick, and d-pad in inventory. @isXander You can do like a switch to change type of d-pad: (Move or shortcuts) or smth like this.
