### ISSUE TITLE
[Bug] Select/Back button does not Change Perspective despite being assigned to do it in Controls.

### ISSUE THREAD

**Issue by muizzsiddique** [isXander/Controlify#128]
### Current Behaviour

Pressing Select/Back in-game does not change camera perspective, it does nothing instead. Binding another button to Change Perspective will change the camera perspective successfully when I press that new button. Binding Select/Back to any other action, like Attack, will successfully perform that action when I press the Select/Back button.

### Expected Behaviour

Without reassigning it, Select/Back should change camera perspective without fail.

### Reproduction Steps

1. On your Steam Deck, load any world.
2. Press the Select/Back button.
3. Observe nothing happening.

### Mod Version

1.4.6+1.20

### Controller

Steam Deck

### Bluetooth

- [ ] Yes

### Operating System

Linux/SteamOS

### ARM

- [ ] Yes

### Additional Information

**Java:** 17.0.7
**Minecraft:** 1.20.1
**Fabric API:** 0.86.1+1.20.1
**Yet Another Config Lib** 3.1.0+1.20
**Mod Menu:** 7.2.1

I specifically tried using only this mod, its dependencies and Mod Menu.

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by Hand-Lock** [comment]
I have the same problem, running macOS on Apple Silicon.

**Comment by isXander** [comment]
This is a conflict with the vmouse button,
