### ISSUE TITLE
[Bug] After using actual mouse, virtual mouse becomes unusable for 5 seconds in Inventory.

### ISSUE THREAD

**Issue by muizzsiddique** [isXander/Controlify#130]
### Current Behaviour

Using mouse in inventory ignores any attempt to move the virtual mouse for 5 seconds.

In other menus, this forced the left stick to function as if virtual mouse is disabled for 5 seconds and therefore the stick navigates the menus like arrow keys. The inventory doesn't use arrow keys so it feels broken for 5 seconds.

### Expected Behaviour

After moving the mouse, the left stick should be able to move the virtual mouse immediately.

A more ideal though arguably pointless behaviour would be to move the virtual mouse using the stick and mouse simultaneously, this would very easily feel instantaneous. Only pointless for non-hybrid users.

### Reproduction Steps

1. Open your Inventory.
2. Mouse your actual mouse (possibly over items and such)
3. Immediately try using the left stick to move the virtual mouse.
4. It will only work once 5 seconds are up.

### Mod Version

1.4.6+1.20

### Controller

Steam Deck

### Bluetooth

- [ ] Yes

### Operating System

Linux/SteamOS

### ARM

- [ ] Yes

### Additional Information

Possibly related to the HUD freeze issue #129 . This will also likely feel less broken if #124 were implemented.

This also could be related to loading a world and not being able to look for a seriously long period of time, but a virtual cursor appears on the screen.

**Java:** 17.0.7
**Minecraft:** 1.20.1
**Fabric API:** 0.86.1+1.20.1
**Yet Another Config Lib:** 3.1.0+1.20
**Mod Menu:** 7.2.1

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isXander** [comment]
This is intended behaviour when using mixed input. The mouse is shown for 5 seconds and then hidden. I could reduce this delay.
