### ISSUE TITLE
[Bug] Crash on startup

### ISSUE THREAD

**Issue by ItzEnderArkail** [isXander/Controlify#141]
### Current Behaviour

it just crashes on startup after i choose the download option

### Expected Behaviour

.

### Reproduction Steps

1. first time boot the game
2. accept/decline download the dependency
3. crash

### Logs

```shell
https://mclo.gs/mqBREhb
```

### Mod Version

1.2.1+1.19.4

### Controller

issues

### Bluetooth

- [ ] Yes

### Operating System

Linux/SteamOS

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isXander** [comment]
This is a very old version of Controlify and this bug has since been fixed.

**Comment by ItzEnderArkail** [comment]
> This is a very old version of Controlify and this bug has since been fixed.
that means 1.19.4 isn't getting the newer versions?

**Comment by isXander** [comment]
Correct!
