### ISSUE TITLE
[Bug] Crash on opening the radial menu

### ISSUE THREAD

**Issue by Hugman76** [isXander/Controlify#147]
### Current Behaviour

I started Minecraft without the controller, then I added my controller via bluetooth and then it got automatically added to the game (really cool stuff ngl)

I played around with the controls, but then when I tried to open the radial menu my game suddently crashed

### Expected Behaviour

The radial should have opened

### Reproduction Steps

- Connect a controller
- Open the radial menu

### Logs

```shell
https://paste.ee/p/nZrLE
```

### Mod Version

v1.5.1+1.20

### Controller

issues

### Bluetooth

- [X] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Additional Information

I used the Nintendo Switch Pro Controller

That happened on the Blanketcon build server
EDIT: after restarting the client right after, the issue is no longer present

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isXander** [comment]
Done in 1.6.0
