### ISSUE TITLE
[Bug] Controller cannot stop vibrating after being killed while holding a bow

### ISSUE THREAD

**Issue by Hugman76** [isXander/Controlify#148]
### Current Behaviour

You can get the controller to constantly vibrate after dying, if you held a bow before dying. I actually got killed by Xander to discover that lol

### Expected Behaviour

The vibration should probably stop as soon as you get killed.

### Reproduction Steps

- Hold a bow and start using it, but do not fire the arrow
- Get killed by something else

### Mod Version

v1.5.1+1.20

### Controller

Nintendo Switch Pro Controller

### Bluetooth

- [X] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Additional Information

The instant respawn gamerule was NOT activated (the death screen popped up), and this occured on the Blanketcon build server.

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isXander** [comment]
Done in 1.6
