### ISSUE TITLE
Controlify crashin steam deck when opening settings

### ISSUE THREAD

**Issue by FroofyFroof** [isXander/Controlify#153]
### Current Behaviour

I open the controller settings for my steam deck in minecraft and it crashes my game with the "display name" thing

### Expected Behaviour

A working mod

### Reproduction Steps

go to controller settings with a steam deck
crashes

### Mod Version

1.6.0+1.20

### Controller

steam deck

### Bluetooth

- [ ] Yes

### Operating System

Linux/SteamOS

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by FroofyFroof** [comment]
its incompatible with sodium, works without
bruh just make it work

**Comment by spudpiggy** [comment]
it's a known issue, disable the error context thing in sodium for now

**Comment by isXander** [comment]
Update to 3.1.1 of YetAnotherConfigLib
