### ISSUE TITLE
[Feature Request] Add an option to force virtual mouse on all screens

### ISSUE THREAD

**Issue by natkos21** [isXander/Controlify#162]
**Is your feature request related to a problem? Please describe.**
Some screens are unusable without virtual mouse (eg. reese's sodium options). I also prefer using virtual mouse.

**Describe the solution you'd like**
An option to force virtual mouse on all screens. Also making it possible to control the mouse using d-pad, and having the mouse behave like box selection without mouse on (including controlling it in inventory)

**Describe alternatives you've considered**
Turning the virtual mouse manually, although it is a lil bit bothersome after a while

**Additional context**
The d-pad control is needed. Option for forcing the virtual mouse would be useful, especially with sodium.

**Comment by isXander** [comment]
When you toggle vmouse for a screen, it is saved permanently. You press it once and it will always remember that screen.
