### ISSUE TITLE
Analog Movement

### ISSUE THREAD

**Issue by ShadowDuude** [isXander/Controlify#166]
**Is your feature request related to a problem? Please describe.**
Whenever I join a server (pvplegacy for example) I get kicked for getting "Invalid Packets" and with analog movement turned off (on https://www.curseforge.com/minecraft/mc-mods/controller-mod) it prevents this while also still allowing you to control everything.

**Describe the solution you'd like**
Adding an way to turn off the way analog movement is used.

**Describe alternatives you've considered**
I've tried finding something in the settings but I don't see anything

**Additional context**
![2023-09-27_22 59 14](https://github.com/isXander/Controlify/assets/146306953/eadfc43c-8376-4f54-829d-4e863b3d740c)

**Comment by isXander** [comment]
This is the keyboard-like movement option.
