### ISSUE TITLE
Using the D-Pad to navigate through the Inventory

### ISSUE THREAD

**Issue by Dan12Aqua** [isXander/Controlify#173]
**Is your feature request related to a problem? Please describe.**
I don't like using the joystick to navigate the inventory, I had a hard time focusing on something I want to find or craft. Worst of all, the speed of the cursor is just atrocious that one small drift would skip the stuff I need, especially crafting.

**Describe the solution you'd like**
Using D-Pad to navigate the inventory.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Ivanoshechka** [comment]
THAT"S WHAT IM TALKING TOO!!!! ( plssss @isXander )

**Comment by natkos21** [comment]
Yep. And add an ability to change "sensitivity" of virtual mouse snapping to elements.

**Comment by MrGreenTea** [comment]
This has already been asked for: #124

**Comment by isXander** [comment]
Duplicate of #124
