### ISSUE TITLE
Minecraft 1.20.1 on Steam Deck with Puzzles Lib installed crashes when opening container

### ISSUE THREAD

**Issue by natkos21** [isXander/Controlify#174]
**Mod Info (fill out the following information)**
- Mod name: Puzzles Lib
- Mod version: v8.0.24 for 1.20.1

**Describe the problem**
Minecraft crashes when opening inventory/any container.

**To Reproduce**
1. Start Minecraft
2. Open/create a world
3. Open inventory/any container
4. Suffer

**Expected behavior**
Opening the container and not crashing.

**Screenshots**
Crash report attached

**Minecraft Info (please complete the following information):**
 - OS: SteamOS
 - Minecraft Version: 1.20.1 Fabric
 - Controlify Version: any 1.20.1 version

**Additional context**
[crash-2023-10-12_00.20.07-client.txt](https://github.com/isXander/Controlify/files/12875020/crash-2023-10-12_00.20.07-client.txt)

**Comment by Xtremeone23** [comment]
Same

**Comment by natkos21** [comment]
https://github.com/Fuzss/puzzleslib/issues/74#issuecomment-1763474716 Here is a temporary workaround, provided by the author of Puzzles Lib
