### ISSUE TITLE
[Bug] (1.7.0 beta 3) Game Crash when opening Chat / Command window OR after extended playtime.

### ISSUE THREAD

**Issue by 31j** [isXander/Controlify#187]
### Current Behaviour

After playing the game for approximately 1 minute, upon opening the chat window (with t or /) the game crashes. IF you play for several nights, block updates will get laggy and the game eventually crashes.

This is without a controller connected, I am just using keyboard / mouse

### Expected Behaviour

The chat window should be accessible and the game should not crash after several nights

### Reproduction Steps

1. Open single player world
2. Idle / play for approx. 1 minute
3. Open chat window / command window (t or / by default)
4. Game crashes 

### Logs

```shell
Crash Report: 
https://mclo.gs/FaI8U5k

Client Log: 
https://mclo.gs/DsoQ3GR
```

### Mod Version

1.7.0-beta.3+1.20.2

### Controller

None/Disconnected

### Bluetooth

- [ ] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by 31j** [comment]
Bug is reproducible on Fedora Linux 38 (same Controlify version, MC version, Fabric API etc. Prism Launcher sourced from flathub)

**Comment by isXander** [comment]
Create another issue if you are having another problem.
