### ISSUE TITLE
[Bug] Dualsense gyro not working on linux

### ISSUE THREAD

**Issue by Garbg** [isXander/Controlify#194]
### Current Behaviour

When I attempt to enable gyro on linux, it says it is not supported, but it is, since it's a dualsense and it works in other games.

### Expected Behaviour

I would expect the gyro feature to work

### Screenshots

![2023-11-20_18 07 27](https://github.com/isXander/Controlify/assets/83542885/4b60095b-b40f-4598-b0d6-61604c4dad8b)
![2023-11-20_18 08 02](https://github.com/isXander/Controlify/assets/83542885/0482618e-59f4-43f3-83b7-b4e8d4cbe142)

### Reproduction Steps

Install the mod on a linux system
Connect a dualsense controller via bluetooth (idk if it works on usb or not)
Launch the game
Go to the gyro section in the advanced settings and see that it says it's not supported

### Mod Version

1.7.0+1.20.2

### Controller

Playstation dualsense

### Bluetooth

- [X] Yes

### Operating System

Linux/SteamOS

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by Garbg** [comment]
It also doesn't work with USB

**Comment by isXander** [comment]
It would be very helpful to get the `latest.log` for this.

**Comment by Garbg** [comment]
> It would be very helpful to get the `latest.log` for this.

Here it is: https://mclo.gs/FxyfWS0

**Comment by Hunkarada** [comment]
I can confirm, same issue with natives installed

**Comment by Hunkarada** [comment]
just updating natives from here (https://github.com/libsdl4j/libsdl4j/releases) don't work to solve this problem

**Comment by Hunkarada** [comment]
btw maybe it will help, in linux dualsense has it's own driver in kernel and kernel recognize it as 2 controllers. 0 is for anything else, than gyroscope, and 1st only for gyro. 
![Screenshot_20240303_135315](https://github.com/isXander/Controlify/assets/69255078/71a768fd-bc7f-4605-8523-64160d8e91ec)

**Comment by isXander** [comment]
I suggest trying out the latest HD haptics test build in the discord server, which uses an updated version of SDL3 which may fix your problems.
