### ISSUE TITLE
Gyro recalibration in settings

### ISSUE THREAD

**Issue by propfeds** [isXander/Controlify#201]
**Is your feature request related to a problem? Please describe.**
Currently, there's a button to recalibrate deadzones in the settings. I can't see why there shouldn't be recalibration available for the gyroscope as well. The first calibration isn't always going to give the best results.

**Describe the solution you'd like**
An 'Automatic Gyro Calibration' button in the Advance tab.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by isXander** [comment]
Recalibrating deadzones also recalibrates gyro. I believe I named it just Calibrate controller?

**Comment by propfeds** [comment]
Okay, so there's an option in the settings called 'Automatic Deadzone Calibration'.
I tried it, and I can confirm that it also recalibrates gyro.
However, it's just called 'Automatic Deadzone Calibration' in the menu. It'd be great if it could be renamed, and preferably also moved to another submenu to avoid confusion.
