### ISSUE TITLE
[Bug] Game crashes when reconnecting controller on Linux

### ISSUE THREAD

**Issue by RoboMico** [isXander/Controlify#202]
### Current Behaviour

I'm using a USB wired Xbox controller and the mod seems to unable to recognize it properly only on Linux platform. The controller is unusable if it's connected before the game launch, but the game crashes whenever I try to reconnect it.

### Expected Behaviour

The controller works fine on Windows and the issue only happens on Linux.

### Reproduction Steps

1. Launch the game
2. Connect the controller, or reconnect it if it already has
3. The game crashes

The issue is reproducible in a fresh new game installation with minimum mod environment:
- Minecraft 1.20.2
- Fabric Loader 0.15.0
- Fabric API 0.91.1
- Controlify 1.7.0
- Mod Menu 8.0.0
- Yet Another Config Lib 3.3.0-beta.1
- MIxinTrace 1.1.1+1.17
- Java 21.0.1, Eclipse Adoptium

### Logs

```shell
Log file: https://pastebin.com/5LgBStG2
Crash report: https://pastebin.com/VndGeBi9
```

### Mod Version

1.7.0+1.20.2

### Controller

Xbox 360 compatible controller

### Bluetooth

- [ ] Yes

### Operating System

Linux/SteamOS

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isXander** [comment]
Hey, @spudpiggy. 
The crash you're experiencing is not the same as the one in this issue, but is likely caused by a conflicting mod that supports Controlify 1.0, (maybe Do-a-barrel-role?)

As for this issue, it was long ago fixed.
