### ISSUE TITLE
[Feature request] Translation

### ISSUE THREAD

**Issue by djibux** [isXander/Controlify#207]
Currently, the mod seems to be only in English.  My kids don’t understand English.  I would like a French translation.

I’m happy to contribute with the translation.

**Comment by Madis0** [comment]
1) Fork the project
2) Copy en_us.json in https://github.com/isXander/Controlify/tree/1.20.x/dev/src/main/resources/assets/controlify/lang to fr_fr.json
3) Edit the file, changing English phrases to French ones
4) Save and commit
5) Make a pull request

**Comment by djibux** [comment]
Just released a PR #212 for that.  I see someone else seems to have pushed another French translation #211 :S  Both translations are not that different from one another.

**Comment by Madis0** [comment]
Well, it is unfortunate that a similar PR appeared few hours before yours but think of it as a way to collaborate. You can comment on each line of changed code so you two can find the best possible translation, and then close one of the PRs (probably yours) to make the mod dev's decision time easier.

**Comment by djibux** [comment]
Just reviewed #211 and closed #212.  Thanks.
