### ISSUE TITLE
Sprinting is not automatically configured on controller [Bug] 

### ISSUE THREAD

**Issue by zoomingspeed** [isXander/Controlify#214]
### Current Behaviour

I am not sure if it is because I have a different keybind for my sprint on my keyboard (which is Q), but when I try to sprint it does not work.

### Expected Behaviour

Clicking down on the joystick while moving it or putting the joystick up twice, I start sprinting, but I do not sprint.

### Reproduction Steps

Try to click down the left joystick but you do not sprint.

### Mod Version

3.1.1, 1.20.1 (Beta)

### Controller

issues

### Bluetooth

- [ ] Yes

### Operating System

Windows

### ARM

- [ ] Yes

**Comment by isXander** [comment]
I've never heard of this issue before, to be clear, you do need to be moving as well as pressing down sprint to start sprinting?

**Comment by zoomingspeed** [comment]
Sorry @isXander, turns out it was from dynamic fov being off 😅
