### ISSUE TITLE
[Bug] Flagging on multiplayer servers

### ISSUE THREAD

**Issue by RealDestroy** [isXander/Controlify#215]
### Current Behaviour

This mod is basically flagging the anticheat on a multiplayer server. It appears to be doing strange movement, also eating is not slowing down the player.

### Expected Behaviour

Just walking around, it appears that the movement is using fastmath maybe to calculate position?

### Reproduction Steps

Install mod
Join server
Get kicked/banned for speed hacking / no slow hacking

### Mod Version

1.7.0+1.20.2

### Controller

issues

### Bluetooth

- [ ] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isXander** [comment]
Controlify does not modify any movement calculations whatsoever. The eating no-slow cannot be caused by controlify.

Analogue movement is the cause of the abnormal movement. Use keyboard-like movement mode to emulate WASD
