### ISSUE TITLE
[Bug] The camera view on the right joystick stops working when the second application window is open

### ISSUE THREAD

**Issue by loveinss** [isXander/Controlify#216]
### Current Behaviour

The camera view on the right joystick stops working when the second application window is open (also minecraft), although all other buttons are working properly. Out of focus input enabled in global settings.

### Expected Behaviour

The camera view with the right sticker on the Dualshock 4 should work, but it does not work when two applications are open.

### Reproduction Steps

Everything was done according to the instructions. I want to play on one computer in 2 windows at once - on one through the controller, on the other the keyboard and mouse.

### Mod Version

1.7.0+1.20.1

### Controller

issues

### Bluetooth

- [ ] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isXander** [comment]
Try turning on `Out Of Focus Input`

<img width="966" alt="Screenshot 2024-01-02 at 12 48 59" src="https://github.com/isXander/Controlify/assets/43245524/68329309-d0c7-40ad-a298-1c5792723e4f">

**Comment by BeardlyBard** [comment]
I am having the same issue. It still does not work even with "Out of Focus Input" checked.

**Comment by BeardlyBard** [comment]
When I move my mouse over to the second screen the view responses correctly. Then when I switch my mouse back to my other screen, the second screen can look around. For some reason that fixes it.

**Comment by BeardlyBard** [comment]
Sorry, for so many in a row. I am just sitting here troubleshooting. When the right stick doesn't work, the player is also not able to break blocks. However, when I move my mouse over everything works normally. Even when I then remove it again. However, any menu resets this and the second screen goes back to not being able to move their head or break anything.

**Comment by Katari-Kityama** [comment]
I'm having the same issue. I play the game with a sibling using 2 windows, my siblings window is out of focus and he is playing with a controller. 
When his window is out of focus, the right joystick stops working after he opens a menu, even after enabling "Out of Focus Input".

**Comment by isXander** [comment]
Seems to be identical to #384 which is now closed, so I will close this too
