### ISSUE TITLE
Crafting

### ISSUE THREAD

**Issue by DenyCrafty** [isXander/Controlify#220]
**Is your feature request related to a problem? Please describe.**
Its annoying to hover over the arrow on the recipe book to go to the other pages. And its generally bad.

**Describe the solution you'd like**
Ideally the crafting system from the legacy console editions ported in some way.

**Describe alternatives you've considered**
If thats to much work maybe at least the function to scroll through the pages with R1/L1.

**Comment by arnokeesman** [comment]
just had a go at the alternative, you can grab the "artifact" from [the actions build](https://github.com/arnokeesman/Controlify/actions/runs/7366603483) to give it a try (let me know if you need it for another version in 1.20.something)

couple months ago some ideas were thrown around in the discord, conclusion basically was: something with more controller convenience is needed

**Comment by isXander** [comment]
> just had a go at the alternative, you can grab the "artifact" from [the actions build](https://github.com/arnokeesman/Controlify/actions/runs/7372555683) to give it a try (let me know if you need it for another version in 1.20.something)
> 
> couple months ago some ideas were thrown around in the discord, conclusion basically was: something with more controller convenience is needed

If you do end up PRing this the `instanceof` check should not be used to provide logic. Check out the `ScreenProcessor` stuff, specifically the `handleScreenVMouse` method.

**Comment by arnokeesman** [comment]
How would I go about creating a ScreenProcessor that applies to all screens that have a recipe book? (`CraftingScreen`, `InventoryScreen`, `FurnaceScreen`, `BlastFurnaceScreen`, `SmokerScreen`(last three can probably be taken from `AbstractFurnaceScreen`) and possibly more)
What they have in common is the interface `RecipeUpdateListener` and they all at some point inherit from `RecipeBookMenu<C extends Container>` (not a `Screen` yet)

**Comment by isXander** [comment]
mixin into `RecipeBookMenu` then!
