### ISSUE TITLE
Sodium Extra Conflict

### ISSUE THREAD

**Issue by apple8404** [isXander/Controlify#228]
**Mod Info**
- Mod name: Sodium Extra
- Mod version: 0.5.3 for Minecraft 1.20.2-1.20.4

**Describe the problem**
Crashes when loading video settings menu.

**To Reproduce**
1. Open video settings with a controller.
2. Win.

**Expected behavior**
Open video settings

**Screenshots**
How about a video instead?
https://youtu.be/AJey-vL1_4c

**Minecraft Info:**
 - OS: Windows 11, Linux (SteamOS)
 - Minecraft Version: 1.20.4
 - Controlify Version: 1.8.0+1.20.4

**Additional context**
In the attached video, I tested on an outdated fabric loader and API version, but it still crashes on current version. I tested on my steam deck as well, where the results were.. different.

I was able to successfully open the video settings menu without crashing on the steam deck, once. I think it's because virtual mouse was enabled from 1.7.0, since I turned off virtual mouse, reloaded the menu, and it crashed again as expected.

Finally, have a log.
[Your logs, milord.log](https://github.com/isXander/Controlify/files/13982927/Your.logs.milord.log)

**Comment by isXander** [comment]
Update to 1.8.1!

**Comment by apple8404** [comment]
1.8.1 fixed issue
the world is saved
