### ISSUE TITLE
Reach-around block placement

### ISSUE THREAD

**Issue by isXander** [isXander/Controlify#23]
Like in bedrock edition, placers should be able to place a block at the end of a bridge even when not looking at the face. This feature is present in both Midnight Controls and Bedrock-ify.

Multiplayer should be considered. When implementing #15, the server should be able to force disable this feature with a toggle to disable in Multiplayer.

**Comment by Madis0** [comment]
Could you make it opt-in rather than opt-out in multiplayer? It could really be considered a cheat in most servers.
