### ISSUE TITLE
List supported controllers

### ISSUE THREAD

**Issue by RaptaG** [isXander/Controlify#24]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A list of supported controller somewhere (e.g. README)

**Describe alternatives you've considered**
🤷🏽‍♂️

**Additional context**
None

**Comment by isXander** [comment]
All controllers work with the mod, they are just unidentified and use the generic XBOX theme.

**Comment by RaptaG** [comment]
Oh alright
