### ISSUE TITLE
Is there a way to turn off the button prompts? 

### ISSUE THREAD

**Issue by thezombiezone** [isXander/Controlify#240]
Can’t seem to find a way to turn them off in the settings or I may be blind. It would be great if you could help me out!

**Comment by Josh65-2201** [comment]
There in Genral > Accessibility > Show button guides

**Comment by thezombiezone** [comment]
> There in Genral > Accessibility > Show button guides

Thank you! Makes the experience on my Steam Deck much cleaner now
