### ISSUE TITLE
Dpad doesn't work on Xbox Series controller[Bug] 

### ISSUE THREAD

**Issue by vcpd1** [isXander/Controlify#251]
### Current Behaviour

I plugged my Xbox Series controller via USB-A/USB-C to my PC. Installed latest version of mod and when I launched the game dpad didn't work in any way.

Software specs:

- GNU/Linux (Ubuntu 23.10, GNOME 45.2, Kernel 6.5.0-21-generic)
- Minecraft 1.20.4 (Prism Launcher)
- Controlify 1.8.1

### Expected Behaviour

Dpad should work

### Reproduction Steps

1. Install Ubuntu 23.10
2. Connect Xbox Series controller
3. Install Minecraft via Prism Launcher
4. Check dpad

### Mod Version

1.8.1+1.20.4

### Controller

Xbox Series Controller

### Bluetooth

- [ ] Yes

### Operating System

Linux/SteamOS

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isXander** [comment]
What Xbox gamepad driver are you using?

**Comment by isXander** [comment]
Stale.
