### ISSUE TITLE
[Bug] settings reset after controller disconnect/connect

### ISSUE THREAD

**Issue by vorzdesigns** [isXander/Controlify#257]
### Current Behaviour

when disconnecting and then connecting controller it loses all the changed settings. I even tried to make the config file read-only but that crashes the game when trying to change key binds or even disconnecting the controller.

### Expected Behaviour

save settings upon clicking the save button.

### Reproduction Steps

1. change settings
2. disconnect controller
3. connect controller again
4. settings reset back to default

### Mod Version

1.8.1+1.20.4

### Controller

issues PS5 Controller

### Bluetooth

- [ ] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by Kevabunch** [comment]
I'm also having this problem with a wired ps5 controller on 1.20.1.

**Comment by isXander** [comment]
Try this on the new 2.0 update, I believe to have fixed it.

**Comment by aekramer** [comment]
> Try this on the new 2.0 update, I believe to have fixed it.

Unfortunately does not seem to be the case, still prompted for a reconfiguration this morning.

It may have something to do with the controller no longer being recognized after firmware update? Should be send over as a Xbox One S Controller from the 2.0 version, but as Wireless Xbox Controller from the previous 1.8

**Comment by isXander** [comment]
the upgrade from 1.8 to 2.0 will cause the reconfig, but from then on, it should never happen. it only goes based off of the USB identifier of a controller which is consistent with models, and the order you connected it to the PC. 

if this still happens, could you repeat the problem, go to global settings > copy debug dump (at the bottom) and paste both before and after into here

**Comment by aekramer** [comment]
Yes I initially reconfigured it but it has reset itself twice now, not sure if it has to do with the controller no longer being identified properly since the firmware update.

I eventually went back to 1.8.1 as I was experiencing some quirkyness and a few crashes last night (not sure if related at all but hasn't happened since going back either) and the vibration settings were better in there

**Comment by isXander** [comment]
Closed in #290
