### ISSUE TITLE
[Bug] Controlify 2.0 Crashes.

### ISSUE THREAD

**Issue by zqpvr** [isXander/Controlify#262]
### Current Behaviour

I join a single player world and it crashes.

### Expected Behaviour

It to not crash.

### Reproduction Steps

Launch Minecraft go to single player and launch a world

### Logs

```shell
https://mclo.gs/mSkZt7e
```

### Mod Version

2.0.0

### Controller

Steam Deck

### Bluetooth

- [ ] Yes

### Operating System

Linux/SteamOS

### ARM

- [ ] Yes

### Additional Information

g

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by SilentException** [comment]
Update Zoomify to 2.13.1.

**Comment by isXander** [comment]
2.13.2
