### ISSUE TITLE
[Bug] 2.0.0 Vibration setting changes

### ISSUE THREAD

**Issue by aekramer** [isXander/Controlify#263]
### Current Behaviour

Since the V2 settings for changing vibrations have changed significantly, and I believe some are not under the right category, for example zooming in using a Spyglass falls under "Effects that are specific to the player" while I find that it would fit under Interaction "using items" much better.

### Expected Behaviour

We should be given much more flexibility in selecting when and where vibrations should occur, for example (from what I can recall on top of my head), this is the perfect behaviour pattern in my eyes:

Vibrations ON:
- Taking damage/being attacked

Vibrations OFF:
- Breaking blocks (player preference, may want this on but on a weaker vibration)
- Using Spyglass
- Walking on Soul sand

Personally I would turn it off for nearly everything besides taking damage, but I can see why people may want it for breaking blocks/eating food, but while using a bow or spyglass its a bit annoying

### Reproduction Steps

Go to settings menu > Vibrations and compare version 1.8 vs 2.0 of the mod

### Mod Version

2.0 + 1.20.4

### Controller

Xbox One S Controller

### Bluetooth

- [X] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by aekramer** [comment]
In addition: Disabling "Allow vibration" entirely still vibrates controls when using something like spyglass/bow

**Comment by isXander** [comment]
Looks like I forgot to make the allow vibration toggle do anything at all!
