### ISSUE TITLE
[Bug] Mixed Input does not work on Controlify 2.0.0-beta.1+1.20.4

### ISSUE THREAD

**Issue by AL2009man** [isXander/Controlify#267]
### Current Behaviour

Even with Mixed Input being enabled: button prompts and controller inputs starts to conflict with each other.

### Expected Behaviour

Aside from Inventory/Crafting conflicting with both input methods, I expected the button prompts to stay on-screen and be able to use Mixed Input.

### Reproduction Steps

1. Enable Mixed Input in Controlify settings
2. use either an Input Remapper and assign Gyro/Trackpad as a Mosue Input, or physically use a Gamepad+Mouse combo.
3. try using both inputs at the same time and the mod will detect and temporarily disable Controller mode.

### Mod Version

2.0.0-beta.2+1.20.4

### Controller

Any

### Bluetooth

- [x] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Additional Information

If playing on Steam Deck: you might need to whip out a Keyboard/Mouse config in case the mod will temporarily disables Controller Mode.

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by pparmy** [comment]
,, I have the same issue . Going to try downloading the previous version as a temp fix for now

**Comment by FabianMPunkt** [comment]
Same issue here on the Steam Deck

**Comment by SilentException** [comment]
IIRC after the 2.0 update it didn't work for me either but I went into controller settings and just cycled through "mixed input" option - turn it off and on again and save - that actually fixed it... who knew :)
