### ISSUE TITLE
Retain settings between controllers of the same type [Re-open] [Bug] 

### ISSUE THREAD

**Issue by aekramer** [isXander/Controlify#276]
### Current Behaviour

The issue of controllers of the same type still overwriting settings is unfortunately still happening even after the 2.0.0 beta.

The original issue was closed, even though a few people have already reported it as still not working. Unfortunately I do not yet know how to reproduce it consistently, however it still happens every other day that it requires a rebinding of all custom configurations.

Link to original issue (can re-open it and close this)
https://github.com/isXander/Controlify/issues/256

### Expected Behaviour

Retain configured settings between controllers of the same type (or even more precisely, the actually same controller is often detected as being new and having to reconfigure it entirely each type, while stock piling the save file with more and more configs each time)

Please provide a way to opt to not use identifiers in the first place and just use the controllers main name (Like Xbox One S Controller) to bind settings to that instead. (Or load add a button to load previous config from same controller type whenever a new controller is detected)

### Reproduction Steps

Simply reconnect a controller every once in a while.

### Mod Version

2.0.0+1.20.4

### Controller

issues

### Bluetooth

- [X] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by protorota** [comment]
Present on macOS too

config resets when controller/ type is connected to pc via usb - either on startup or during gameplay

Ability to save and load config settings would be a great feature

**Comment by Dimmidice** [comment]
Resetting here as well, just got a conflict between kbm & controller. Reconnected controller and everything was reset again. It's one big flaw with this mod, other that than i'm absolutely loving it.

**Comment by isXander** [comment]
Alright I have identified the problem. What I did to close the previous issue was correct and should have solved the issue, however now another issue has arose that was not properly removing controllers once they had disconnected, making the UID think it was controller 2. I will fix this now.
