### ISSUE TITLE
Do a barrel role Conflict with v2

### ISSUE THREAD

**Issue by Josh65-2201** [isXander/Controlify#287]
**Mod Info (fill out the following information)**
- Mod name: Do a barrel role
- Mod version: 3.5.4

**Describe the problem**
I'm uncertain whose side this is on so I have posted on both https://github.com/enjarai/do-a-barrel-roll/issues/136
Crash report: https://mclo.gs/JMd0zv0

**To Reproduce**
1. Install both mods
2. Connect an Xbox control
3. Minecraft will freeze and crash

**Expected behavior**
Not to crash and have both mods work as normal

**Minecraft Info (please complete the following information):**
 - OS: Windows 11 build 22621.3374
 - Minecraft Version: 1.20.1
 - Controlify Version: 2.0.0 beta 3

**Comment by isXander** [comment]
This is a DABR issue and should be tracked there.
