### ISSUE TITLE
[Controller Request] Xbox One S Controller

### ISSUE THREAD

**Issue by aekramer** [isXander/Controlify#292]
**Controller name**

Xbox One S Controller

**Conroller VID & PID**

[13:28:34] [Render thread/WARN]: Controller found via USB hardware scan, but it was not found in the controller identification database! (HID: HID[VID=0x045e, PID=0x0b20])
[13:28:34] [Render thread/INFO]: Controller connected: 'Xbox One S Controller'#SDL-1-HID[VID=0x045e, PID=0x0b20] (null)

This controller was previously detected just fine, the name is also correct. Used to be detected as a "Xbox Wireless Controller" previously, but due to a firmware update (required to fix some issues regarding bluetooth connectivity on windows 11) it is no longer in the identification database.

The controls and everything functions as intended, just not recognized. If the identifier is added to the other xbox controllers list it will probably use the correct icon for it again and stop asking.

I have previously selected the "Submit Data" when prompted in-game while using this mod. If any other information is required please let me know.

**Comment by isXander** [comment]
Looks like I have been neglecting the database a bit!
![chrome_WBfhB8xpul](https://github.com/isXander/Controlify/assets/43245524/9352fa8f-39d0-4889-a40c-c84dea34e4fe)
