### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by road2react** [isXander/Controlify#293]
![image](https://github.com/isXander/Controlify/assets/93143714/d37f9ad4-fd48-496e-bbdd-97a2b4ce1ace)

https://github.com/isXander/Controlify/blob/5d75b80387458638c0b087dbdcc02e98f7efb4fb/src/main/java/dev/isxander/controlify/screenop/ScreenProcessor.java#L41

Each instance of ScreenProcessor registers another callback, which references the ScreenProcessor, which references DownloadingTerrainScreen, which references a world. These callbacks are never cleaned up, leaking memory.

**Comment by isXander** [comment]
Thanks for debugging this, will take a look
