### ISSUE TITLE
[Bug] DualSense controller not working over bluetooth

### ISSUE THREAD

**Issue by TheCrafter8000** [isXander/Controlify#302]
**Is your feature request related to a problem? Please describe.**

I would like to see support for the DualSense controller through bluetooth as a large precent of people using this mod would most likely use it to sit back in their couch or chair and other people may not have a long cord to reach their PC.

**Describe alternatives you've considered**

The only alternative is using the controller wired or using ds4windows which only emulates the dualshock controller wirelessly

**Comment by isXander** [comment]
I commonly use my DualSense controller over bluetooth with Windows and Mac. No external software required.

**Comment by isXander** [comment]
Could you explain how exactly it isn't working? Is the controller not detected? Do the inputs not work?

**Comment by TheCrafter8000** [comment]
I did more testing and when I disable ds4windows entirely, the mod will detect the dualsense over bluetooth, but when I use ds4 windows and disable the virtual controller in the setting the mod doesnt detect the dualsense over bluetooth. Not sure if this is an issue with your mod or just the way ds4windows works
