### ISSUE TITLE
Crash On Start

### ISSUE THREAD

**Issue by renatocs81** [isXander/Controlify#304]
### Current Behaviour

I tried loading my ModPack with Controlify, but it crashes.

### Expected Behaviour

I expected it to work.

### Screenshots

No Screenshots Because Instant Crash

### Reproduction Steps

1. Load ModPack with Controlify.
2. karma/Crash

### Logs

```shell
I've already loaded ModPack without Controlify, sorry.
(Don't Worry, I might crash the game again when I feel like adding a crash report/log.)
```

### Mod Version

Minecraft: 1.20.1. Mod Loader: Fabric 0.15.10. Mod Version: 2.0.0 Beta 5

### Controller

Keyboard/Laptop (Not Importatnt)

### Bluetooth

- [ ] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Additional Information

The latest version of Minecraft is 1.20.6 but I need to use 1.20.1 because it is the 1.20 Minecraft version with the most mods so ignore the thing that says "I have made sure I am using the latest version of Controlify for the latest version of Minecraft."

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by renatocs81** [comment]
Could you please ignore the random color blue on the bug log characters?

**Comment by bashbarnard** [comment]
I'm also getting this on steam deck. 1.20.5 version worked fine. 1.20.6 no longer working. Can't control at all. Touch controls enable me to be able to get into menus and controller settings are still there. Just won't open. I hope this is some help at least

**Comment by isXander** [comment]
I still have no crash report.
