### ISSUE TITLE
[Bug] On-Screen Keyboard Causes FPS to Drop

### ISSUE THREAD

**Issue by TheCrafter8000** [isXander/Controlify#308]
### Current Behaviour

Whenever you open chat and the keyboard popus up, my fps drops to around 5 and then the keyboard becomes laggy and randomly unresponsive.

### Expected Behaviour

not to lag at all

### Reproduction Steps

Open Chat
Watch FPS Drop

### Mod Version

Controlify-2.0.0-beta.5+1.20.4

### Controller

DualSense

### Bluetooth

- [X] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Additional Information

When using the d-pad on the keyboard it feels delayed in a sense. Pressing it every second is fine but as soon as you start pressing it a little faster it just doesnt respond.

This is a feature enhancement but i would also like to see buttons keybinds for things like the space bar and backspace just like how playstation and xbox work. For example, Square for backspace, triangle for space, and L1 and L2 for moving cursor left and right.

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by TheCrafter8000** [comment]
weirdly enough, if the window is smaller then the fps only reduces to about 20 and the delay thing is barely there

**Comment by Lncvrt** [comment]
yeah i got this too

**Comment by Lncvrt** [comment]
@isXander

**Comment by Lncvrt** [comment]
not a conflict issue either.i enabled (this mod), fabricapi, modmenu, yetanotherconfig lib

**Comment by Lncvrt** [comment]
this is on 1.21 btw
