### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by justwannatokyo** [isXander/Controlify#309]
### Current Behaviour

when I enter a single world, everything is fine, but as soon as I touch the controller, the game crashes

### Expected Behaviour

crashes when I enter the world

### Reproduction Steps

crashes when I enter the world

### Logs

```shell
https://mclo.gs/asz0sVf
```

### Mod Version

2.0.0-beta.8+1.20.1

### Controller

ds4

### Bluetooth

- [X] Yes

### Operating System

Windows

### ARM

- [X] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by justwannatokyo** [comment]
I'm still waiting

**Comment by isXander** [comment]
Update zoomify
