### ISSUE TITLE
Legacy4J Conflict

### ISSUE THREAD

**Issue by KateReller** [isXander/Controlify#310]
**Mod Info (fill out the following information)**
- Mod name: Legacy4J
- Mod version: 1.6.2a fore 1.20.4

**Describe the problem**
The game crashes on startup.

Crashlog: https://mclo.gs/eos3kdr

**Minecraft Info (please complete the following information):**
 - OS: AtlasOS (Modified Windows 11)
 - Minecraft Version: 1.20.4
 - Controlify Version: 2.0.0-beta.8

**Comment by isXander** [comment]
Fixed in Legacy4J 1.6.3

**Comment by TomerGamerTV** [comment]
There still seems to be some issues, buttons seem to double press (such as trying to switch items skips 1 instead of going in order) or trying to select menu buttons switches between them so fast they don't click
