### ISSUE TITLE
Detect and help setup Steam Deck

### ISSUE THREAD

**Issue by Madis0** [isXander/Controlify#32]
**Is your feature request related to a problem? Please describe.**
From what I've heard, Steam Deck has controller simulation but mods are better. So Controllify could detect the OS and help the user set things up with the mod.

**Describe the solution you'd like**
Detect the OS and help user with the setup.

**Describe alternatives you've considered**
N/A

**Additional context**
Idk, maybe you already do it. I don't have Deck so don't ask me to test it though.

**Comment by isXander** [comment]
Decks work out of box in controller mode, just like any other gamepad.
