### ISSUE TITLE
[Bug] Game crash when opening radial menu

### ISSUE THREAD

**Issue by OKHI233** [isXander/Controlify#325]
### Current Behaviour

Game crash when opening radial menu.

### Expected Behaviour

Game would not crash when opening radial menu.

### Reproduction Steps

1. Enter a world.
2. Open radial menu.

### Logs

```shell
https://gist.github.com/OKHI233/3f9d86512796575bcdb18c68b31a4086
```

### Mod Version

2.0.0-beta.10+1.20.1

### Controller

Xbox Series S|X Wireless Controller (https://www.xbox.com/en-US/accessories/controllers/xbox-wireless-controller-usb-c)

### Bluetooth

- [ ] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Additional Information

The controller is connected with a USB Type-C cable. Firmware version 5.20.7.0 (latest at the time of writing).

This issue is introduced in 2.0.0-beta.9+1.20.1, Quilt loader have no impact on this as the same thing also happens on Fabric. I'm not sure if other game versions also have the same issue.

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by mineTomek** [comment]
I have a similar error message but when just clicking the button to set up the radial menu.

**Comment by annathelibri** [comment]
I have the same crash with same error message, both when setting up the radial menu as well as accidentally opening it.

Controller is DualShock 4, through Bluetooth on Windows.

Happening on beta.10+1.20.1, just freshly installed it.

**Comment by ArchOwlen** [comment]
+1 Same issue here

Logs don't specify anything specific

Steam Deck 
2.0.0-beta.10+1.20.1

**Comment by isXander** [comment]
Cannot repeat.

- Controlify 2.0 beta 10
- Quilted Fabric 7.5.0-0.91.0 (as seen in the log)
- YetAnotherConfigLib 3.4.4+1.20.1-fabric

**Comment by lostdoge08** [comment]
> Cannot repeat.
> 
> * Controlify 2.0 beta 10
> * Quilted Fabric 7.5.0-0.91.0 (as seen in the log)
> * YetAnotherConfigLib 3.4.4+1.20.1-fabric

Im getting the same crash as well, same version and all that. Maybe its a mod incompatibility issue? Here's the full log. 
[crash-2024-06-11_17.08.37-client.txt](https://github.com/user-attachments/files/15795243/crash-2024-06-11_17.08.37-client.txt)

**Comment by OKHI233** [comment]
> Cannot repeat.
> 
> * Controlify 2.0 beta 10
> * Quilted Fabric 7.5.0-0.91.0 (as seen in the log)
> * YetAnotherConfigLib 3.4.4+1.20.1-fabric

Hi,

I think I know where the issue is. The "Toggle HUD Visibility" action is for some reason, broken in the 1.20.1 version (in 1.20.6 it works normally). If I unbind it through editing the configuration file, the game will no longer crash, and I cannot bind it in the config menu.

Hope that would help tracking down the issue.

**Comment by lostdoge08** [comment]
> > Cannot repeat.
> > 
> > * Controlify 2.0 beta 10
> > * Quilted Fabric 7.5.0-0.91.0 (as seen in the log)
> > * YetAnotherConfigLib 3.4.4+1.20.1-fabric
> 
> Hi,
> 
> I think I know where the issue is. The "Toggle HUD Visibility" action is for some reason, broken in the 1.20.1 version (in 1.20.6 it works normally). If I unbind it through editing the configuration file, the game will no longer crash, and I cannot bind it in the config menu.
> 
> Hope that would help tracking down the issue.

Yep, I removed that option on the wheel in the config file and it fixed it.

**Comment by mineTomek** [comment]
Hey, @OKHI233, can I just ask what do you mean by
> If I unbind it through editing the configuration file, the game will no longer crash, and I cannot bind it in the config menu.

I tried changing it to an empty string or something random like `controlify:none` and when loading the game it just reverts it back to the default configuration.
