### ISSUE TITLE
[Bug] dr web finds a virus in controlify

### ISSUE THREAD

**Issue by TheKveilan** [isXander/Controlify#326]
### Current Behaviour

in the latest versions of controlify dr web finds a virus

### Expected Behaviour

not one of the known antiviruses will find the virus

### Screenshots

![изображение](https://github.com/isXander/Controlify/assets/151543343/12eaab44-130e-42b1-bee2-df1060c6bb88)

### Reproduction Steps

download controlify from github - curse forge - modrinth
go to the total virus or dr web online check site and download the controlify mod 

and see a complaint about the virus

### Mod Version

Controlify-2.0.0-beta.10+1.20.6

### Controller

xbox series s - x controller

### Bluetooth

- [X] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by yum13241** [comment]
Of course it's going to be detected as a Java.Downloader, it DOWNLOADS sdl2 natives. Have you ever heard of something called a false positive? (Pro tip: if a file is only detected by a few anti-viruses, it's probably not a virus.)
