### ISSUE TITLE
1.0.0+1.19.4 - Mod crashes when clicking on Controller settings

### ISSUE THREAD

**Issue by Nincodedo** [isXander/Controlify#33]
**Describe the bug**
Game crashes when going to settings.

**To Reproduce**
1. Go to Options -> Controls -> Controller Settings...
2. The game crashes

**Expected behavior**
A menu of settings.

**Log**
https://mclo.gs/9y4SWOx

**Comment by Ivanoks** [comment]
Download [YetAnotherConfigLib](https://modrinth.com/mod/yacl/version/2.3.0), it's fixed my problem.
