### ISSUE TITLE
[F.Req] Documentation for how to make a Controlify resource pack.

### ISSUE THREAD

**Issue by yum13241** [isXander/Controlify#332]
**Is your feature request related to a problem? Please describe.**
I would like to change how the buttons look.

**Describe the solution you'd like**
Clear documentation for how to make a Controlify resource pack. Using other packs as a base is legally questionable and does not help tell you where you need to put XBox buttons, where to put Switch buttons, so on. (See the "Steam Deck glyphs" pack on Modrinth for example).

If I were to take the pack and try to rename the "steam_deck" to "xbox_one", it wouldn't work. Without the required documentation (whi h is nowhere on the wiki), pack makers have a harder time making their packs, since they don't know the names of the required foldera.

**Describe alternatives you've considered**
Trying to read through every single line of code without dying of boredom.

**Additional context**
None.

**Comment by isXander** [comment]
Documentation is planned, but during the beta period, this is changing a lot, so I am waiting for it to become stable before taking the time to write documentation.

**Comment by yum13241** [comment]
Could you at least tell me where I would put XBox buttons in a resource pack? Thanks.

**Comment by apple8404** [comment]
If you have 7Zip installed, you can extract the Controlify jar file. From there, you can find an "assets" folder that more or less will tell you the structuring of the entire resource pack format.

This is the same exact process used for vanilla Minecraft resource packs.

**Comment by isXander** [comment]
It's not `/textures/gui/`, it's `/textures/font/`
