### ISSUE TITLE
Sprinting never stops

### ISSUE THREAD

**Issue by RoberbufDx8105** [isXander/Controlify#334]
### Current Behaviour

When I press the left thumbstick it starts sprinting, but when I press it once again, it doesn't stop.
I tried to fixing it by setting Hold on the options menu, but it still doesn't work.
Only way to stop this is by pausing the game and pressing B right after.
Have I only got this issue? If not, is there any solution?

### Expected Behaviour

I expected to stop sprinting when I press the left thumbstick while sprinting.

### Screenshots

I don't know how to make a recording filming both Minecraft and an online controller tester to show the inputs.

### Reproduction Steps

1. Press left thumbstick to sprint.
2. Pressing another time the left thumbstick, you will NOT stop sprinting.

### Mod Version

2.0.0-beta.10+1.20.6

### Controller

DualShock 4

### Bluetooth

- [ ] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isiah-lloyd** [comment]
I also have this issue on Steam deck. 1.20.6  (.9 beta)using the built in controller. 

I ended up unbinding sprint entirely and exclusively using double tap forward on the left thumb stick to sprint.

**Comment by RoberbufDx8105** [comment]
Btw I also tried an Xbox 3rd party controller and the same thing happens.
I'm using Fabric + Fabric API, does that help?

**Comment by rllynotfox** [comment]
I'm having the same problem. I play on  1.20.6 with xbox series controller connected with wires.

**Comment by rllynotfox** [comment]
I fixed it by downgrading to beta-8, now everything works as its supposed to
