### ISSUE TITLE
[Suggestion] Allow user to make buttons guide bottom.

### ISSUE THREAD

**Issue by Ivanoshechka** [isXander/Controlify#34]
`Is your feature request related to a problem? Please describe.`
I see first time, what the hud on the top of the screen. This kind of throws me off. For me, it will be better, if the guide buttons was at the bottom on screen. (And I think that many people will like the bottom one...)

`Describe the solution you'd like.`
Add in the global settings the "hud side". You can make default the top side, but add additional the bottom. It will be great solution.

**Comment by Ivanoks** [comment]
Thanks, so..
About chat, you can you can lift it up a bit. I Think, it will be nice.
About the hand: nothing to do? If this gonna be so asf, we always have options to make hud again on top. 
I still think about to do buttons guide bottom as an additional option.

**Comment by Mamsikas** [comment]
in my case, the hints overlap the coordinates, which is very disturbing.
In the chat, it's just better to move higher

**Comment by KennyDevT** [comment]
yeah honestly you could  just allow user to place it bottom and give a warning
