### ISSUE TITLE
[Bug] wont connect to external server with mod enabled

### ISSUE THREAD

**Issue by Vantablack3301** [isXander/Controlify#347]
### Current Behaviour

when launching on the steam deck and connecting to a self hosted server, the game will automatically crash.

### Expected Behaviour

its supposed to enter the server

### Reproduction Steps

install 24w14potato via prism, add the fabric mod loader via the install loader button, add the controllify mod in the mods tab. launch, connect to a server of the same version number.

### Mod Version

2.0.0+24w14potato

### Controller

issues

### Bluetooth

- [ ] Yes

### Operating System

Linux/SteamOS

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by Vantablack3301** [comment]
[aditional logs](https://github.com/user-attachments/files/15832579/logs.txt) for more info

**Comment by isXander** [comment]
This was fixed in a later version and I don't think I'm up for supporting these april fool versions. The latest 1.20.6 version might work with [a dependency override](https://fabricmc.net/wiki/tutorial:dependency_overrides)
