### ISSUE TITLE
D-pad gameplay works in inventory.

### ISSUE THREAD

**Issue by Ivanoks** [isXander/Controlify#35]
**Describe the bug**
While you in the inventory, you can use d-pad keybindings. (Like open the chat, change the camera, drop somethings.)

**To Reproduce**
1. Go to the world.
2. Open the inventory.
3. Press the d-pad.
4. See error.

**Expected behavior**
I think cursor gonna move on the slots.

**Screenshots**

https://user-images.githubusercontent.com/88715280/226169361-8db8ba9c-be78-4c13-9791-66fab1c700e9.mp4

(Sorry for the breath, I thought I muted the mic. Xd)

**Minecraft Info (please complete the following information):**
 - OS: Windows 10 pro.
 - Minecraft Version: 1.19.4 [quilt, 0.18.5]
 - Mod Version: 0.1.0+1.19.4

**Additional context**
Add the cursor move on the slots with d-pad?

**Comment by isXander** [comment]
events no longer pass through and drop works as expected in inventories.

**Comment by Ivanoks** [comment]
You made cursor move on slots on dpad?
