### ISSUE TITLE
crash when trying to access controller settings [Bug] 

### ISSUE THREAD

**Issue by aquaiipip** [isXander/Controlify#350]
### Current Behaviour

everything works totally okay, except when i try to open the controller settings. game goes "saving world" despite not even opening a world in the first place and crashes.

### Expected Behaviour

going into controller settings without crashing

### Reproduction Steps

1. go to the mods tab
2. choose controlify and go to the mods settings
3. click settings on the new window that popped up
game crashes at this point.

### Mod Version

1.8.1+1.20.4

### Controller

xbox series controller

### Bluetooth

- [X] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by DoigtdePOULET** [comment]
Hi! I'm having the same issue. I'm running on 1.20.1, with only Controlify 1.6 (latest release) and YetAnotherConfigLib 3.6.2 and ModMenu 7.2.2. 

Everything is working fine, but when I access the Setting menu of Controlify, the game goes ''saving world'' and then. closes. 

Any idea?

**Comment by YounessX3** [comment]
please can you fix this problem like why is it even a problem nobody talking about it
