### ISSUE TITLE
Game crashes when pressing R1 in controller settings menu

### ISSUE THREAD

**Issue by MattyOfficial** [isXander/Controlify#352]
### Current Behaviour

When you're on the settings page for your controller pressing R1 to change tabs will crash the game. You can still change tabs with the arrows.

### Expected Behaviour

You should be able to change tabs when pressing R1.

### Reproduction Steps

1. Go to Options > Controls > Controller Settings > Settings
2. Press R1
3. Game crashes

### Mod Version

2.0.0-beta.13+1.21-fabric

### Controller

Dualshock 4

### Bluetooth

- [X] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by DioEgizio** [comment]
Can reproduce too with DualSense on Linux
