### ISSUE TITLE
[Bug] Using D-Pad Up to navigate the cursor in the inventory causes the chat to open

### ISSUE THREAD

**Issue by mserajnik** [isXander/Controlify#359]
### Current Behaviour

When using the D-Pad to navigate the inventory cursor and hitting D-Pad Up (which by default is bound to open the chat) the chat will open once the inventory is closed.

I can see in #35 that this should already be fixed, but the issue is still occuring.

### Expected Behaviour

D-Pad Up (or any other bound button that's used for inventory cursor navigation) should not open the chat (or trigger any bound actions) when in the context of navigating the inventory.

### Reproduction Steps

1. Open the inventory
2. Move the cursor by hitting D-Pad Up (making sure D-Pad Up is bound to open the chat)
3. Close the inventory
4. Observe the chat being opened

### Mod Version

Controlify 2.0.0-beta.13 for Fabric 1.21

### Controller

[DUALSHOCK 4 Wireless Controller](https://www.playstation.com/en-gb/accessories/dualshock-4-wireless-controller/)

### Bluetooth

- [X] Yes

### Operating System

macOS

### ARM

- [X] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by apple8404** [comment]
Can also confirm this happening on an Xbox controller with D-Pad Left bound as chat.

**Comment by aekramer** [comment]
Yes, this didn't used to be the case originally (1.8 and early v2 beta, not sure when it started), I don't have it assigned to chat anymore but use custom keybinds for some mods that get triggered and turned on/off constantly while going through inventory/chests.

It would be great if d-pad keybinds can be disabled while viewing item containers or other interfaces
