### ISSUE TITLE
Hint Buttons Icon [Bug] 

### ISSUE THREAD

**Issue by salexhx** [isXander/Controlify#363]
### Current Behaviour

Hello!
i think it doesn't need any explanation and the issue is visible.

### Expected Behaviour

just normal visible icons.

### Screenshots

![Untitled](https://github.com/isXander/Controlify/assets/71204370/b5398154-6341-4bf6-a6ee-616d9e9b3a4d)

### Reproduction Steps

it's visible in everywhere of game like gameplay, menus, etc.

### Mod Version

1.2.1 + 1.19.4

### Controller

Twin USB Gamepad

### Bluetooth

- [ ] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Additional Information

Minecraft Version 1.19.4
Fabric Mod Loader
Controlify Version 1.2.1 + 1.19.4
YACL Version 3.0.3 + 1.19.4

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isXander** [comment]
Unfortunately 1.19.4 is no longer supported by Controlify and is not receiving updates. This specific bug has been fixed in later versions.
