### ISSUE TITLE
Touch controls

### ISSUE THREAD

**Issue by Madis0** [isXander/Controlify#37]
**Is your feature request related to a problem? Please describe.**
Java Edition does not have full touch controls

**Describe the solution you'd like**
Add touch controls that look and behave like Bedrock Edition.

**Describe alternatives you've considered**
A separate mod?

**Additional context**
-

**Comment by isXander** [comment]
GLFW does not support multi-touch. Which I feel is a necessary feature to make touch controls not awful to use. Additionally, there are no good places where touchscreen would be necessary to use.

- Mobile (Pojav) - Already has keyboard emulation overlay built-in with multi-touch
- Touchscreen laptops - Keyboard + Trackpad is much better than trying to use Minecraft with your thumbs on a 13 inch screen
- Steam Deck - has a built-in gamepad *and* mouse emulation trackpad thing
