### ISSUE TITLE
[Bug] Out of Focus breaks after opening any gui

### ISSUE THREAD

**Issue by HideyBoi** [isXander/Controlify#384]
### Current Behaviour

When using the out of focus mode, the controller is no longer able to control the camera after closing any gui (inventory, chests, pause, chat, any create menu)

### Expected Behaviour

After closing the gui you should be able to move your camera

### Reproduction Steps

1. Enable out of focus mode
2. Ensure that the game window is not focused
3. Open the inventory
4. Close the inventory and try to look around

### Mod Version

2.0.0-beta.13  1.20.1-fabric

### Controller

issues

### Bluetooth

- [X] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Additional Information

Issue occurs on both PS4 and Nintendo Switch Pro Controllers
Issue occurs regardless if bluetooth is being used or not

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isfwdf** [comment]
MacBook Pro M2 (aarch64)
OpenJDK Runtime Environment Temurin-21.0.4+7
Fabulously Optimized 6.1.0-alpha.3 (controlify 2.0.0-beta.14)

Same problem here, occurs both on Flydigi Direwolf 2 (connected via bluetooth, act as Xbox One controller)
Steam Controller (act as Xbox 360 controller)

After loosing camera controls, Right Stick are still correctly working in game menu (for sliders) and in Radial Menu from mod.

**Comment by J4PC** [comment]
### This is an essential feature for split screen. 

Because of this issue, the use of Controlify for split screen is unpractical (one player cant turn the camera). 

I hope this gets fixed soon.

**Comment by HideyBoi** [comment]
This needs to get fixed asap!! One of the bigger draws of controller mods imo is split screen, but without that feature working it's literally unplayable.
