### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by RyanCR03** [isXander/Controlify#39]
Game crashes on startup

**To Reproduce**
Open game
Crash

**Expected behavior**
The game starting

**Screenshots**
![image](https://user-images.githubusercontent.com/32957560/230277779-d95a6662-6d55-4771-9798-cc78206e6da8.png)

**Minecraft Info (please complete the following information):**
Windows 10
1.19.4
1.0.0 beta.2

**Additional context**
[crash-2023-04-06_00.09.38-client.txt](https://github.com/isXander/Controlify/files/11166619/crash-2023-04-06_00.09.38-client.txt)

**Comment by isXander** [comment]
Controlify requires YetAnotherConfigLib.

**Comment by RyanCR03** [comment]
should probably be marked as a dependency
