### ISSUE TITLE
1.20.1 NeoForge Support

### ISSUE THREAD

**Issue by alinco8** [isXander/Controlify#399]
**Is your feature request related to a problem? Please describe.**
There is no Controlify for Neoforge 1.20.1.

**Describe the solution you'd like**
Support 1.20.1 NeoForge

**Describe alternatives you've considered**
Use Controllable  ->  Mod buttons are not working and other problems occur.

**Additional context**
I like Controlify because it doesn't conflict with other mods! I know there's a lot of work involved, but I really hope NeoForge becomes compatible with 1.20.1!

**Comment by tbSRoe** [comment]
I would also be very interested 🥰

**Comment by CCF100** [comment]
+1 for (Neo)Forge support! I want to play a modpack on my Steam Deck that targets 1.20.1

**Comment by isXander** [comment]
Do Lexforge mods not work on Neoforge 1.20.1?

**Comment by genderneutralnoun** [comment]
+1 for this.

**Comment by alinco8** [comment]
It seems that support for NeoForge (=Forge) version 1.20.1 requires significant effort and will not be provided. 😢

**Comment by alinco8** [comment]
@genderneutralnoun 

Sorry for closing it the wrong way!

According to Xander in https://discord.com/channels/780023008668287017/780095378166513674/1305800809769861192, supporting 1.20.1-Forge seems to be too much effort, so I thought it might not happen.

**Comment by alinco8** [comment]
@isXander 
> Do Lexforge mods not work on Neoforge 1.20.1?

I looked it up but couldn’t find it, so what is it?
