### ISSUE TITLE
Add item distributing/spreading in containers

### ISSUE THREAD

**Issue by jaymehta-g** [isXander/Controlify#400]
**Is your feature request related to a problem? Please describe.**
With the mouse, you can grab a stack with your cursor in a container and drag left click to evenly distribute the items, or drag right click to distribute 1 item to each slot. This functionality is missing with controller support.

**Describe the solution you'd like**
Holding VMouse LClick and VMouse RClick buttons should act the way they do with the actual mouse with distributing items in the container gui

**Comment by jaymehta-g** [comment]
Seems to be implemented in the 1.21 version

**Comment by GitEmulate** [comment]
> Seems to be implemented in the 1.21 version

Please tell me how. I've tried everything that I can think of, but I can't spread items at all, neither the "1 item per slot" way or the even distribution way. 

I'm using a regular Xbox One controller on the default bindings. If I try to press A (VMouse LClick) and X (VMouse RClick) at the same time while holding items, it just places down half of what I'm holding. I tried many different bindings, even using the "VMouse Key Shift" and LClick at the same time it didn't work. 

This is driving me crazy.

Oh wait, you don't need to use the Shift key at all (Did they change it in an update or was I just always doing it incorrectly?). When I'm using a real mouse, it works just fine. I hold down left-click to spread evenly and right-click to drop one item per slot. But when I use the controller, it just doesn't work. When I hold down A, it places everything in the one slot, as if I had only clicked and not held it down. Same for right-clicking, it just places the one item.

I am using the latest versions, Controlify 2.1.1 in Minecraft 1.21.5.
