### ISSUE TITLE
Steam Deck gyro controls

### ISSUE THREAD

**Issue by mubinulhaque** [isXander/Controlify#406]
**Is your feature request related to a problem? Please describe.**
Steam Deck gyroscope support has not been added yet, due to the fact that it wasn't exposed outside of Steam Input. SDL has finally implemented a method for exposing the API [here](https://github.com/libsdl-org/SDL/pull/8212).

**Describe the solution you'd like**
We should either use the API exposed [here](https://github.com/libsdl-org/SDL/pull/8212) to implement native gyroscope controls on Steam Deck, so that it has feature parity with every other controller compatible with this mod.

**Describe alternatives you've considered**
There is also SteamDeckGyroDSU, plus the current method of emulating Gyro as Mouse via Steam Input.

**Additional context**
If we're using SDL3, the corresponding PR is [here](https://github.com/libsdl-org/SDL/pull/8211).

**Comment by isXander** [comment]
Unfortunately the SDL PRs are for when the Steam Client is not enabled (running custom OS on steam deck for windows or other distros).

Fortunately, I have been cooking something up, and I can mark this as resolved (:
