### ISSUE TITLE
[Bug] Feeding Animals Not Working Legacy4j On FeatherServer

### ISSUE THREAD

**Issue by Gobblerss** [isXander/Controlify#415]
### Current Behaviour

When i feed my animals i get spam kicked after i added the Legacy4j mod

### Expected Behaviour

I can feed my animals fine without getting kicked

### Screenshots

I dont have any because i just found this website

### Reproduction Steps

s

### Logs

```shell
s
```

### Mod Version

1.21.1

### Controller

Plastation 3 controller and keyboard and mouse

### Bluetooth

- [X] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Additional Information

s

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isXander** [comment]
Legacy4j also includes controller support, these will be conflicting. You're gonna have to pick one or the other
