### ISSUE TITLE
Can't set custom bind

### ISSUE THREAD

**Issue by TomyGamy** [isXander/Controlify#42]
**Describe the bug**
When I press a bind to change it, the label change to "Press any button", and when I do an action on the controller, it works for the menu (like cursor moving or going to the previous menu) but don't register the new bind

**Screenshots**
![image](https://user-images.githubusercontent.com/95078425/230509611-d632c7c7-0a35-4255-865e-871afafd662f.png)

**Minecraft Info (please complete the following information):**
 - OS: [Windows 11
 - Minecraft Version: 1.19.4
 - Mod Version: v1.1.0-beta.2

**Additional context**
I tried with an USB PS3 controller and an Xbox One controller connected with Bluetooth.

**Comment by isXander** [comment]
Try navigating to the bind with your controller, rather than the mouse, press A and rebind. This will be fixed in the next beta.

**Comment by RaptaG** [comment]
> This will be fixed in the next beta.

Has it though? I mean if yes, this should be closed
