### ISSUE TITLE
[Bug] Mixins crash on startup

### ISSUE THREAD

**Issue by Josh65-2201** [isXander/Controlify#422]
### Current Behaviour

Note: The log box doesn't allow uploading the log
[latest.log](https://github.com/user-attachments/files/17305937/latest.log)

### Expected Behaviour

Game should open

### Reproduction Steps

1. Open game

### Mod Version

1.20.1 - 2.0.0 beta 14

### Controller

Xbox Series S

### Bluetooth

- [X] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by josh0x10c** [comment]
Can confirm, run into the exact same issue on 1.20.1 - 2.0.0 beta 14.
1.20.1 - 2.0.0 beta 13 works fine for me.
Running this on the Steam Deck in my case.

**Comment by Josh65-2201** [comment]
Fixed with beta 17
