### ISSUE TITLE
[Bug] Controlify crashes game when added to modpack

### ISSUE THREAD

**Issue by An0therOne** [isXander/Controlify#425]
### Current Behaviour

Whenever I try to launch the game with the mod enabled, it crashes and sends the exit code 1 error.

### Expected Behaviour

To launch as normal.

### Screenshots

![Screenshot_120](https://github.com/user-attachments/assets/72bb424d-5387-4064-91fe-cde4d7fc9640)

### Reproduction Steps

1. Go to Minecraft Launcher
2. Launch Fabric.
3. Crashes.
4. Exit error message.
5. Cry in pain.

### Mod Version

Controlify-2.0.0-beta.14+1.20.1

### Controller

issues

### Bluetooth

- [ ] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by SpectralHauntings** [comment]
I've found beta.14 crashes on 1.20.1 no matter what. Try downgrading to beta.13 I've found it works without issue

**Comment by An0therOne** [comment]
Has the creator noted this issue?
