### ISSUE TITLE
Chat Patches Conflict

### ISSUE THREAD

**Issue by baseb01** [isXander/Controlify#432]
**Mod Info (fill out the following information)**
- Mod name: Chat Patches
- Mod version: 211.6.9 for 1.21.1 Fabric

**Describe the problem**
Chat patches shifts the chat upwards as well as the hover elements associated with each line, however when controlify is installed the hover elements are where they used to be even though the chat is still shifted upwards.

**To Reproduce**
1. Have both Chat Patches and Controlify installed
2. Go to chat and hover over any line of text
3. No hover element will show up until you move mouse down a bit further

**Expected behavior**
Hover elements show up at correct location which is what happens when controlify is not installed.

**Screenshots**
![image](https://github.com/user-attachments/assets/d523e4b9-71dc-412f-8e01-31dc50ff58b6)

**Minecraft Info (please complete the following information):**
 - OS: Windows 10
 - Minecraft Version: Minecraft 1.21.1 Fabric 0.16.7
 - Controlify Version: 2.00-beta.17 1.21-fabric

**Additional context**
I spoke to the chat patches mod creator @mrbuilder1961 and he believes the issue needs to be fixed from your side.

**Comment by AncientYears** [comment]
Also seem to be getting without chat patches/other mods enabled. Strange

**Comment by HaXrDEV** [comment]
Sounds a bit like the same issue as https://github.com/isXander/Controlify/issues/246

**Comment by baseb01** [comment]
Fixed as of beta 21
