### ISSUE TITLE
[Bug] 1.21 Fabric: Controlify can't apply virtual mouse mixin, leading to a crash

### ISSUE THREAD

**Issue by terraquad** [isXander/Controlify#446]
### Current Behaviour

Game crashes after launching

### Expected Behaviour

It shouldn't

### Reproduction Steps

1. Create a new Fabric 1.21 instance with only Controlify installed
2. Launch the instance

### Logs

https://mclo.gs/EacBrCg

### Mod Version

2.0.0-beta.19+1.21

### Controller

None, Steam Deck

### Bluetooth

- [ ] Yes

### Operating System

Windows, SteamOS

### ARM

- [ ] Yes

### Additional Information

Tried launching on two devices with the same outcome

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by GreenGhost21** [comment]
Similar with 2.0.0-beta.20 on 1.20.1, again with a fresh install with only Fabric, Controlify, and dependencies.

https://mclo.gs/jWw4VzW

**Comment by NoIDidntHackU** [comment]
same for me in 1.21.1:
https://mclo.gs/xAO64v9

**Comment by notrohit1702** [comment]
2.0.0 beta 21 should fix this

**Comment by terraquad** [comment]
> 2.0.0 beta 21 should fix this

Confirmed to work
