### ISSUE TITLE
[Controller Request] <8Bitdo Pro 2>

### ISSUE THREAD

**Issue by TurtleFanCoder** [isXander/Controlify#464]
**8Bitdo Pro 2**

**VID=0x045e, PID=0x02e0**

It detects it as an Xbox controller (which most things do) but this thing was built with gyro, and I'd love to be able to use gyro with it :D

**Comment by TurtleFanCoder** [comment]
I formatted it wrong but yeah....
Also seems someone has already asked for this but it wasn't done. Apparently SN30 pro is compatible so lemme try that and see if the gyro works

**Comment by TurtleFanCoder** [comment]
SN30 Pro also is picked up as an Xbox controller and does not support gyro.

**Comment by vos6434** [comment]
If the mod supports switch gyro then yes it should

**Comment by TurtleFanCoder** [comment]
I tested the Pro 2 and the gyro is detected, but no matter what way I turn the controller or what options I have, the camera just moves down and a little to the right. Gonna try the SN30 to see if its better

**Comment by TurtleFanCoder** [comment]
Same issue with the SN30, though turns up and to the left a little.

**Comment by TurtleFanCoder** [comment]
Figured it out! You have to reboot the game any time to modify the gyro settings. (You might only have to rejoin the world) a bit annoying, but super fun to mess with! Sorry for the inconvenience of being stupid...
