### ISSUE TITLE
Crash when initializing controllers

### ISSUE THREAD

**Issue by xleb-normal** [isXander/Controlify#49]
**Describe the bug**
Minecraft crashes after the end of loading with the version 1.1.0-beta.3+1.19.4

**To Reproduce**
1. Install version 1.1.0-beta.3+1.19.4
2. Run minecraft
3. Wait for the end of loading
4. See the error

**Expected behavior**
Launching Minecraft

**Minecraft Info:**
 - OS: Linux Mint 21.1 x86_64
 - Minecraft Version: fabric-loader-0.14.19-1.19.4
 - Mod Version: 1.1.0-beta.3+1.19.4

**Additional context**
logs
[latest.log](https://github.com/isXander/Controlify/files/11276412/latest.log)

**Comment by Xleby4ek** [comment]
Will it be fixed?

**Comment by isXander** [comment]
Yes.
