### ISSUE TITLE
D-Pad for GUIs, or "inputs that basically do the same thing"

### ISSUE THREAD

**Issue by NyaomiDEV** [isXander/Controlify#51]
**Is your feature request related to a problem? Please describe.**
The really annoying feeling of not being able to use the D-Pad on menus.

**Describe the solution you'd like**
Please make the D-Pad usable for GUIs, ALONGSIDE the left analog stick or whatever is already mapped; this might just be best done by "binding the same function twice", even though that's something no one wants to show in any configuration screen, I guess.

**Describe alternatives you've considered**
Left stick is fine, it just doesn't line up with some people's muscle memory.

**Additional context**
In Bedrock you can use both the left stick and the D-Pad to navigate through menus.

**Comment by nousernameyetlol** [comment]
Yeah, I hope this gets added too

**Comment by Ivanoks** [comment]
We **need** it.

**Comment by Crackers0106** [comment]
Yes please, really throws me off cause I use the d-pad to navigate menus when I play any game with a controller
