### ISSUE TITLE
You can't control YACL slider values with a controller

### ISSUE THREAD

**Issue by NyaomiDEV** [isXander/Controlify#52]
**Describe the bug**
While you can press the A button and move the left stick to assign a new value in a slider using vanilla slider options, you cannot do the same on YACL menus (including Controlify's own configuration screen). This is an issue.

**To Reproduce**
1. Go to the Controlify config screen
2. Look for a slider value
3. Try to change it with a controller, WITHOUT using the virtual mouse
4. See the UX error

**Expected behavior**
Clicking A and then going left and right with the stick should decrease or increase the slider value.

**Screenshots**
Not really applicable.

**Minecraft Info (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.19.4
 - Mod Version: 1.1.0-beta.3+1.19.4

**Additional context**
It's also an issue with Sodium

**Comment by isXander** [comment]
You use the right stick left/right.

**Comment by NyaomiDEV** [comment]
Well, this then causes a consistency issue. If any other slider is modified by using the left stick but the ones in YACL, people are going to get confused at best.
