### ISSUE TITLE
Minecraft 1.19.4 - Crash on Startup

### ISSUE THREAD

**Issue by Soufre** [isXander/Controlify#55]
The game immediately closes when attempting to execute Controlify 1.1.0-beta.3+1.19.4, even when using YetAnotherConfigLib 2.4.1

_**The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'controlify'!**_

Crash report.
[crash-2023-04-20_17.49.00-client.txt](https://github.com/isXander/Controlify/files/11291344/crash-2023-04-20_17.49.00-client.txt)

**Comment by isXander** [comment]
This is due to https://github.com/enjarai/do-a-barrel-roll In beta 3, the API changed.

**Comment by isXander** [comment]
DABR has been PRd and should be fixed soon.
