### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by t0ssox** [isXander/Controlify#61]
**Describe the bug**
Controlify crashing on startup. First it shows prompt about vibrations, then it just crashing my instance. I also tried to run with quilt but it didn't changed anything.

**To Reproduce**
1. Download and install onto the instance: Controlify 1.1.0+1.19.4 ; FabricAPI 0.80.0+1.19.4 ; YetAnotherConfigLib 2.5.0+1.19.4
2. Run instance
3. Be sad

**Expected behavior**
Game is not crashing and I can enjoy some gamepad gameplay.

**Screenshots**
Black screenshot propably will not help in this case.

**Minecraft Info (please complete the following information):**
 - OS: Arch Linux
 - Minecraft Version: 1.19.4
 - Mod Version: 1.1.0+1.19.4

[error.log](https://github.com/isXander/Controlify/files/11368650/error.log)
[crash-2023-05-02_01.19.40-client.txt](https://github.com/isXander/Controlify/files/11368653/crash-2023-05-02_01.19.40-client.txt)

**Comment by isXander** [comment]
What controller are you trying to use?

**Comment by isXander** [comment]
The crash is fixed in next update, but this will still prevent you from using controller.

**Comment by t0ssox** [comment]
> The crash is fixed in next update, but this will still prevent you from using controller.

Just Xbox Wireless Controller.

**Comment by isXander** [comment]
In this log it appears that GLFW doesn't think your controller is a gamepad but a joystick.
