### ISSUE TITLE
If controller is not enabled by default, prompt for vibration thing when the first one is 

### ISSUE THREAD

**Issue by Madis0** [isXander/Controlify#63]
**Is your feature request related to a problem? Please describe.**
The vibration thing supposedly pops up on first game launch regardless if there is a controller enabled. This is fine for users who install the mod manually, but is not fine for modpacks.

**Describe the solution you'd like**
If a modpack has enabled the setting to make controllers opt-in, show that vibration prompt only when a first one gets connected and calibrated, in the same wizard flow.

> for example, I'd make it a part of this process
> 
> after the calibration is done, you ask: 
> > Would you like to also enable controller vibration support? 
> > This will download a small helper program in the size of X MB. Vibration will be enabled for all controllers and can be changed at any time in controller settings.

**Describe alternatives you've considered**
Could make it a part of the calibration flow for everyone, not just those who set controller support to be opt-in

**Additional context**
You know what I'm referring to 😄

**Comment by isXander** [comment]
Writing this down for myself:
This is slightly difficult because the natives are currently loaded before initializing any controllers, and hotplugs expect everything to be initialised.
