### ISSUE TITLE
Crash with Controlify 1.2

### ISSUE THREAD

**Issue by Xleby4ek** [isXander/Controlify#72]
**Describe the bug**
The game closes with error 1 if you use Controlify 1.2

**To Reproduce**
1. Starting minecraft with Controlify 1.2
2. See error

**Expected behavior**
Load minecraft with not errors

**Minecraft Info:**
 - OS: Linux Mint 21.1 x86_64
 - Minecraft Version: fabric-loader-0.14.19-1.19.4
 - Mod Version: Controlify-1.2.0+1.19.4-fabric-1.19.4

**Additional context**
logs 
[latest.log](https://github.com/isXander/Controlify/files/11480824/latest.log)

**Comment by isXander** [comment]
This log appears to be either due to fabrishot or memory leak fix. Not to do with Controlify.

**Comment by Xleby4ek** [comment]
> Этот журнал, по-видимому, связан либо с исправлением fabrishot'а, либо с утечкой памяти. Не имеет отношения к Controlify.

I have removed these mods, but minecraft still crashes, but when you remove Controlify, minecraft starts in normal mode
[latest.log](https://github.com/isXander/Controlify/files/11499735/latest.log)

**Comment by isXander** [comment]
Does it work with just Controlify, YACL and Fabric API? If so, find the mod culprit by doing the following:

With just the above mods in your folder, add half of the remaining mods back, if the issue occurs, remove half of what you added and repeat. If it doesn't occur add the new half of unloaded mods back and repeat. Let me know the culprit.

**Comment by isXander** [comment]
Fixed in 1.2.1

**Comment by Xleby4ek** [comment]
For some reason, the game crashes anyway, although I tried to download from 1.2.1, but in earlier versions (1.1.1) the game started quietly, I also attached a log
[2023-05-19-4.log](https://github.com/isXander/Controlify/files/11518660/2023-05-19-4.log)

**Comment by Xleby4ek** [comment]
> Does it work with just Controlify, YACL and Fabric API? If so, find the mod culprit by doing the following:
> 
> With just the above mods in your folder, add half of the remaining mods back, if the issue occurs, remove half of what you added and repeat. If it doesn't occur add the new half of unloaded mods back and repeat. Let me know the culprit.

It work with just Controlify, YACL and Fabric API

I also realized because of which mod the game was crashing - **Optifine**, **Optifabric**
