### ISSUE TITLE
Crashes when taking damage - rumble issue when no controller is present.

### ISSUE THREAD

**Issue by mineblock11** [isXander/Controlify#73]
**Describe the bug**
The game crashes when the player takes damage and no controller is plugged in.

https://mclo.gs/qcSOFr5

**To Reproduce**
1. Take damage.
4. See error/crash

**Expected behavior**
No crash.

**Minecraft Info (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.19.4
 - Mod Version: ![](https://i.imgur.com/TIYTDXQ.png)

**Comment by isXander** [comment]
```
java.lang.NullPointerException: Cannot invoke "dev.isxander.controlify.rumble.RumbleManager.play(dev.isxander.controlify.rumble.RumbleEffect)" because the return value of "dev.isxander.controlify.controller.Controller.rumbleManager()" is null
```

**Comment by isXander** [comment]
Try 1.2.0?

**Comment by mineblock11** [comment]
I can't reproduce this at all with 1.1.0 or 1.2.0 - maybe it was just an edge case. Closing for now.
