### ISSUE TITLE
Crash with optifine

### ISSUE THREAD

**Issue by Xleby4ek** [isXander/Controlify#75]
**Describe the bug**
The game closes with error 1 if you use Controlify 1.2 / 1.2.1 and optifine, optifabric

**To Reproduce**

   Starting minecraft with Controlify 1.2 / 1.2.1 and optifine, optifabric
   See error

**Expected behavior**
Load minecraft with not errors as it was with version 1.1.1

**Minecraft Info:**

   OS: Linux Mint 21.1 x86_64
   Minecraft Version: fabric-loader-0.14.19-1.19.4
   Mod Version: Controlify-1.2.1+1.19.4-fabric-1.19.4
   Optifine: OptiFine_1.19.4_HD_U_I4
   Optifabric: optifabric-1.13.24

Additional context
logs
[latest.log](https://github.com/isXander/Controlify/files/11522964/latest.log)

**Comment by isXander** [comment]
No support is currently given to optifine.
