### ISSUE TITLE
Minecraft crashes with some controllers

### ISSUE THREAD

**Issue by Lolothepro** [isXander/Controlify#81]
**Describe the bug**
Minecraft crashes with some controllers

**To Reproduce**
1. Use Minecraft with a Thrustmaster Dual Analog 4 controller

**Minecraft Info (please complete the following information):**
 - OS:  Ubuntu 22.04
 - Minecraft Version: 1.19.4
 - Mod Version: 1.2.1+1.19.4

**Additional context**

[latest.log](https://github.com/isXander/Controlify/files/11638524/latest.log)
[crash-2023-06-02_22.08.02-client.txt](https://github.com/isXander/Controlify/files/11638527/crash-2023-06-02_22.08.02-client.txt)

**Comment by isXander** [comment]
Will be fixed in next update (1.20)
