### ISSUE TITLE
Allow simultaneous Mouse/Controller input

### ISSUE THREAD

**Issue by FabianMPunkt** [isXander/Controlify#84]
**Is your feature request related to a problem? Please describe.**
I'm using the Steam Deck and in many games i have SteamInput setup, so that the Right-Trackpad and the Gyro use "As-Mouse" as their input method. Some games don't care if there is Mouse-input and Joystick-input at the same time, but other games  go completely haywire when they see different inputs being used.
Unfortunately, it seems like that Controlify stops all input from a given device, when an input from another device is recognized.

The same thing applies to keyboard inputs that are simultaneous to any controller inputs.

**Describe the solution you'd like**
I think there should be an option like "Allow simultaneous Mouse / Controller input"
With this enabled the game continues to accept inputs from all devices / controllers, and just "mixes" them together (also including keyboard inputs etc..)

**Describe alternatives you've considered**
Setting the Gyro and Trackpad to "Joystick" in SteamInput works aswell, but "As-Mouse" just feels sooooo much better xD
This isn't an issue in [MidnightControls ](https://github.com/TeamMidnightDust/MidnightControls) btw.

**Additional context**
Would such a solution be possible?

Edit: using v1.3.0-beta.2+1.20

**Comment by rbits0** [comment]
This did not occur in older versions of Controlify. Something must have changed. This is a must have for the Steam Deck, I cannot play without gyro/trackpad

**Comment by SilentException** [comment]
I also noticed this today after switching to Controlify. The biggest issue is if you keep using the mouse (trackpad) long enough, the Controller will stop being in use and disconnect. So you need to find your way to pause the game (bind esc) and navigate through settings to click "Use"... Hoping this could be fixed, it was not an issue in neither MC or Controllable.

**Comment by Triory** [comment]
https://github.com/isXander/Controlify/blob/c5c7a3775f475c8c5b750aa6d8c14adf3a2f75f6/src/main/java/dev/isxander/controlify/InputMode.java
👀 pog

**Comment by isXander** [comment]
Next release will include this for steam deck only.

**Comment by SilentException** [comment]
Thanks, this includes keyboard as well? Today I've noticed that holding one of my back buttons on SD that I have mapped to keyboard key interferes with joystick the same way as trackpad.

**Comment by isXander** [comment]
Yes, includes keyboard.
