### ISSUE TITLE
Dualshock 4 gyro behaves as a joystick on Linux

### ISSUE THREAD

**Issue by Kekker-git** [isXander/Controlify#85]
**Describe the bug**
Dualshock 4 gyro behaves as a joystick instead of a mouse on Linux. It has a "neutral" position, and when it is rotated past that position, it causes continuous camera rotation that increases in speed as the controller rotates further from that neutral position.

**To Reproduce**
1. Install Controlify in Minecraft 1.20 on Linux
2. Plug in Dualshock 4 and start the game
3. Enable gyroscope in controller settings
4. Watch as the camera spins out of control

To see the joystick-like behavior, reduce the gyro sensitivity to 5% and rotate the controller until it reaches a position where the camera stops moving. Then, you can rotate the controller a tiny bit, hold it there, and see that the camera continues to move as if a joystick had been moved a little bit past the deadzone.

**Expected behavior**
The gyroscope should behave as a mouse. All camera movement should be based on relative controller rotation: if the controller moves a little bit, then stops, the camera should do the same.

**Screenshots**
![Sensitivity settings](https://github.com/isXander/Controlify/assets/10159040/c526e986-5b8e-4cd9-b8a9-455ea978b982)
![Button bind](https://github.com/isXander/Controlify/assets/10159040/4582d377-4b0f-49ec-ac10-c0673ecdb2b0)
[Video of the issue](https://www.youtube.com/watch?v=tG1mj6g41CQ)

**Minecraft Info (please complete the following information):**
 - OS: Arch Linux 6.2.1 with X11 (KDE Plasma)
 - Minecraft Version: 1.20
 - Mod Version: 1.3.0-beta.2+1.20

**Additional context**
My controller will be recognized as a generic "Wireless Controller Touchpad" if I start the game with the controller connected via Bluetooth. If I start the game wired, it is recognized as a Dualshock 4, but the "Wireless Controller Touchpad" is still present in the controllers menu. The generic controller does not support gyro or rumble, so I don't think it is interfering, but it is there regardless.

**Comment by isXander** [comment]
Is this still a problem in 1.3.1?
