### ISSUE TITLE
A key is register twice when exiting a inventory menu

### ISSUE THREAD

**Issue by TomyGamy** [isXander/Controlify#88]
So I set the same key for exiting my inventory and drop an item in game, so when I press it, it exit the menu but it also drop my main hand item

**Expected behavior**
It should exit the menu without droping the item

**Minecraft Info (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.20
 - Mod Version: 1.3.0+1.20

**Comment by TomyGamy** [comment]
Well it does it with otre menu, like the pause menu

**Comment by Oranamous** [comment]
Can confirm this is also an issue for me, I'm used to the classic control scheme from legacy console edition so I set the B button to both drop and exit ui and it drops whatever I'm holding whenever I exit a menu.

**Comment by spudpiggy** [comment]
bump cus this sounds bad

**Comment by Bitslayn** [comment]
Still an issue

**Comment by s-liwka** [comment]
bump

**Comment by isXander** [comment]
Forgot to mark #219 as a duplicate but this if fixed.
