### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by Moosbee** [isXander/Controlify#90]
**Is your feature request related to a problem? Please describe.**
I'm writing a Mod and I want to add Controlify support. Is there some sort of API Documentation I can use to quick start the process of implementing support?

**Describe the solution you'd like**
An "API.md" Markdown File containing the main functions and a guide to implement support in ones own mod and to add it as a dependency. 

**Describe alternatives you've considered**
I also accept "go figure it out yourself" as answer, even if I don't like it. Using this Issue as Documentation is possible as well.

**Comment by isXander** [comment]
Updated documentation recently.
