### ISSUE TITLE
"Incompatible Mod Set"

### ISSUE THREAD

**Issue by sebcoolan** [isXander/Controlify#91]
I'm having an issue with starting up Minecraft with the Controlify mod. Here's the error code:
![Screenshot 2023-06-17 080839](https://github.com/isXander/Controlify/assets/136900421/8aa7296f-7035-4066-b7ca-cc012025a7ce)
And the Minecraft log: 
![Screenshot 2023-06-17 080854](https://github.com/isXander/Controlify/assets/136900421/759d1777-e9dd-42e9-b601-9ab38dc74602)
And finally, The mods I currently have:
![Screenshot 2023-06-17 080917](https://github.com/isXander/Controlify/assets/136900421/a5bc681b-1d8c-4213-abac-817d7f624d75)
I don't know what to do in this case. Please help me.
Specs:
GPU:3070 (laptop)
CPU:intel i7 12k
Ram:16gb ddr5
SSD:512gb
HHD:1TB
OS: Windows 11 home.

**Comment by isXander** [comment]
install yet another config lib

**Comment by sebcoolan** [comment]
How do you install a "config lib". And where to install it? Its my first time using fabric mods

**Comment by isXander** [comment]
https://modrinth.com/mod/yacla1
