### ISSUE TITLE
Vibration only partially works on ROG Ally

### ISSUE THREAD

**Issue by upstroke-version** [isXander/Controlify#92]
**Describe the bug**
vibration feature only partially works on ROG Ally, which is detected as XInput Gamepad on controlify.
for example, "Test vibration" on settings and vibration via "Take Damage" trigger works perfectly, 
however, vibration doesn't work when destroying blocks on survival or creative world.

**Minecraft Info (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.20.1
 - Mod Version: 1.3.0+1.20

**Comment by isXander** [comment]
If you turn the vibration strength up to 200%, does it work?

**Comment by upstroke-version** [comment]
Sorry for a very late response, haven't been playing Minecraft for awhile, and now I'm playing again.
Cranking the strength of every vibration settings to 200% did help, but it is still very weak and barely noticeable.
I'm not sure what would be the cause of this issue, since in other games the vibrations feels great, but perhaps offering a option to crank the percentage even more(like 400 or maybe 1000%) with a warning for a user might be a decent workaround...?

**Comment by isXander** [comment]
The test vibration is as strong as it can get unfortunately. Any stronger maxes out the byte assigned to the driver.

**Comment by upstroke-version** [comment]
after testing for few more days, I thinks vibrations are normal...ish. when breaking most blocks vibration is quite weak but it does exist, and when braking blocks like obsidian vibration is noticeably strong. I will close this issue.
The "test vibration" button doesn't do anything on my device tho, which is weired but that's a issue I can live with.
