### ISSUE TITLE
Some Keys not working at same time

### ISSUE THREAD

**Issue by YAPPYawesome** [isXander/Controlify#96]
**Describe the bug**
certain keys stop working when controller is active

**To Reproduce**
1. Activate controller
2. Press spacebar on keyboard
3. Nothing happens

**Expected behavior**
whats assigned to spacebar (jump) should happen

**Minecraft Info (please complete the following information):**
 - OS: Steam OS
 - Minecraft Version: 1.20.1
 - Mod Version: 1.3.1 +1.20

**Comment by isXander** [comment]
Why are you using keyboard emulation with the Deck with Controlify?

**Comment by YAPPYawesome** [comment]
> Why are you using keyboard emulation with the Deck with Controlify?

When playing with mods there could be tons of different controls and sometimes there’s keys that are conditional. For example the shift key could be do 3 different things depending on the situation  and what other Keys are pressed at the same time. So in those situations I prefer to just use steam input to bind shift to one of the back buttons. Or sometimes I bind multiple keys to one button to create these situational bindings. For example I like binding some random key to right stick that will show me recipe in JEI or other such mods while still having normal R3 bonded to it for changing POV.

**Comment by isXander** [comment]
Was fixed in 1.3.2
